### ISSUE TITLE
On Label purchase, make sure user can't accidentally click and buy a second label

### ISSUE THREAD

**Issue by nabsul** [Automattic/woocommerce-services#1016]
https://wordpress.org/support/topic/two-labels-purchased/#post-9161430

Based on the conversation above, it seems that it might be possible to click "BUY" in that time between successfully making a first purchase and closing the modal.

**Comment by jeffstieler** [comment]
I can confirm that this is possible - if your connection is too fast, you can use Chrome's developer tools to throttle the speed (under Network tab).

**Comment by dechov** [comment]
`state.form.isSubmitting` turns false when the [label purchase response comes in](https://github.com/Automattic/woocommerce-services/blob/a059559475dc129aeba36f48e112c9efc31f32a9/client/shipping-label/state/actions.js#L472), again inviting the user to "Buy & Print" until the document to print is loaded, at which point the [printing flow is exited](https://github.com/Automattic/woocommerce-services/blob/a059559475dc129aeba36f48e112c9efc31f32a9/client/shipping-label/state/actions.js#L508).

Is there some way to preserve the error handling while bringing those actions closer together? Otherwise, do we want another disabled state after "Purchasing..." such as "Loading..." / "Downloading..."?

**Comment by jeffstieler** [comment]
I don't think we sacrifice error handling by decreasing the time between those action dispatches.

The delay looks to be caused by the `printDocument()` call. I'm thinking that we should look into either not clearing `form.isSubmitting` on successful purchase responses, or moving the success notice and flow exit actions to before `printDocument()`, or both.
