### ISSUE TITLE
500 Internal Server Error when buying label

### ISSUE THREAD

**Issue by ahalekelly** [Automattic/woocommerce-services#1074]
I'm getting this 500 Server Error error whenever I try to buy any labels, anyone know what's going on?

    wcc_server_error_response Error: The WooCommerce Services server returned: Internal Server Error An internal server error occurred ( 500 )
    (WC_REST_Connect_Shipping_Label_Controller)`

**Comment by nabsul** [comment]
Hi @ahalekelly ,

I'm seeing the following error on the server side: "The transaction was declined. Please try another card."

Are you sure the card you selected in the configuration is still valid? If this doesn't help, please let me know and I'll dig deeper. I'll also look into making it so that the plugin returns a more meaningful error message in this situation.

Cheers.

**Comment by ahalekelly** [comment]
Whoops you're right, that was it. Thanks.

**Comment by nabsul** [comment]
Glad to hear it!
