### ISSUE TITLE
Unable to open Create New Label dialog

### ISSUE THREAD

**Issue by ahalekelly** [Automattic/woocommerce-services#1075]
I have one order that won't let me open the Create New Label dialog, the page fades out but there's no window. Here's the content of the Chrome debug console:

![image](https://user-images.githubusercontent.com/7078138/27806758-834a721c-600a-11e7-99ca-1ae40f236aad.png)

And there's nothing in the debug log.

**Comment by jeffstieler** [comment]
@ahalekelly are you able to access the metadata for that order? If so, does it have a value for `wc_connect_packages`?

If you're unable to access the metadata, any information about the order will be helpful. Did the customer use a WCS-based live rate to checkout with? etc.

Thanks!

**Comment by ahalekelly** [comment]
Sorry, how do you access the metadata?

They did use a WCS-calculated shipping rate during checkout. I noticed one of the items had no dimension information, but after adding it, the problem is still there.

**Comment by jeffstieler** [comment]
@ahalekelly - I'm sorry you've been affected by this bug. It seems to be caused by a bug in some code in WooCommerce 3.1.0, and a lack of resilience to it in our plugin.

WooCommerce 3.1.1 will resolve the issue completely, but in the meantime we'll work towards an intermediate fix that will allow you to print labels, but won't auto-select the packaging chosen by the customer.

My apologies for the trouble!

**Comment by jeffstieler** [comment]
WCS devs:

I think the solution is to better handle bad data in [`get_packaging_from_shipping_method()`](https://github.com/Automattic/woocommerce-services/blob/master/classes/class-wc-connect-shipping-label.php#L107). The bug is causing the packaging data to be stored as `a:1:{i:0;N;}` in the database.
