### ISSUE TITLE
Products Are not Packed into Separate Packages when setting is toggled

### ISSUE THREAD

**Issue by keninbassart** [Automattic/woocommerce-services#1229]
Customer reported issue on 790910-zd-woothemes

When customer sets up products to ship individually, and has the option toggled to "Ship items individually, in their original packaging." the products will always return a single rate no matter how many products are in the cart. 

It appears that it may be related to this issue  ( https://github.com/Automattic/woocommerce-services/issues/1157 ) as it seems to not be taking the size into consideration either. However toggling the "Ship Individually" setting should bypass the box packer all together and calculate each item on it's own. 

For the customer's site I logged into test site and checked all the settings. Customer does have "ship individually" selected and does have products configured with the dimensions and weights as they should.  

I created a test product that wasn't a Subscription just to rule that out and have the same issue. 

I created a test product on my test site with the same dimensions and was not able to get it to load more than one rate either no matter how many products I added to the cart. 

Test Site Settings

Settings:

![settings1](http://cld.wthms.co/JBRon3+)

![settings2](http://cld.wthms.co/gFal4w+)

packages

![package](http://cld.wthms.co/dM6EUC+)

Product:

![shipping](http://cld.wthms.co/ikUC5a+)

Cart:

![cart](http://cld.wthms.co/5M8Rgi+)

**Comment by jeffstieler** [comment]
It appears that the bug here is that a Priority Flat Rate service is being quoted when "Ship items individually, **in their original packaging.**" is selected. _(Priority Flat Rate services require the use of specific USPS packaging)_

Here's a test I did with the same product dimensions _(8 x 11 x 0.01)_:

![](https://cldup.com/sDNYNGY-G_-3000x3000.png)

![](https://cldup.com/alHz41uYsR-3000x3000.png)

You can see that the non-flat-rate service goes up by a multiple of the cart quantity. While the flat rate shouldn't be quoted - it is accurate. Two products of that dimension will fit in a Medium box.

**A workaround for this issue is to disabled flat rate services for the shipping method instance that has "ship individually" chosen**

**Comment by laurendavissmith** [comment]
Closing since we're not focusing on live rates at the moment
