### ISSUE TITLE
Automated taxes not automating

### ISSUE THREAD

**Issue by stephhjacq** [Automattic/woocommerce-services#1259]
Automated taxes are not applied to product in cart/checkout

ticket ref: 823481-zen

Replicated on my Pressable site with shop base New Jersey, selling to Missouri, should be charged at 4.220%

![http://cld.wthms.co/G33U7N](http://cld.wthms.co/G33U7N+)
Full Image: http://cld.wthms.co/G33U7N+ 

Also tested shop base BC, Canada, selling to BC, Canada should be 12% but showed 0. 

Log shows `TaxJar Plugin requested :::: (WCS Tax)`, nothing more.

**Comment by jeffstieler** [comment]
> shop base New Jersey, selling to Missouri, should be charged at 4.220%

You should only have to collect Missouri sales tax if you have a "tax nexus" (physical location of sorts) in Missouri. Since WCS only supports one nexus (the shop base location), taxes will only apply to sales made in the same state - the appropriate rates based on the customer's location will be used.

For more info, see:
https://www.taxjar.com/states/new-jersey-sales-tax-online/
https://www.taxjar.com/states/missouri-sales-tax-online/

**Comment by stephhjacq** [comment]
Thanks @jeffstieler
