### ISSUE TITLE
Pulling Package Types

### ISSUE THREAD

**Issue by BurlesonBrad** [Automattic/woocommerce-services#1280]
After reading the [WooCommerce Services Docs](https://docs.woocommerce.com/document/woocommerce-services), I got a question from one of the members of [**WooHelp FB Group**](https://www.facebook.com/groups/woohelp):
**"_When will they be adding more package sizes and options?_"**
At which point I thought back on the T-Shirt shipping days & looked for some of the "First Class" Envelopes. I kinda scratched my head a bit at the layout & workflow.  So, I want you to consider following along with me here from a WooCommerce Business Owner's Point Of View.  

Here's what the user is prompted for under the **```RATES```** area

![woocommerce-services](https://user-images.githubusercontent.com/6208757/34947705-8ae77866-f9d0-11e7-8997-34d85f3887db.png)
Wait, hold on a second.  🤔 If we're prompting a store owner to select which ```RATE``` they want, most are going to select First Class Mail. It's the cheapest, easiest, and most efficient USPS rate for most store owners.

So, why is the option **```First-Class Mail - Large Envelope```** being presented ❓ 

➡️ **FIRST-CLASS MAIL** ⬅️  is a RATE
and
▶️ **LARGE ENVELOPE** ◀️ is a PACKAGE

Shouldn't that prompt be pulling **ONLY** the rate?  _(watch and I'll show 'ya **WHY**)_

Because then **after** choosing "I need to use the of First Class rate", then the user goes over to the **"PACKAGES"** screen only to find this:
![woocommerce-services-packages](https://user-images.githubusercontent.com/6208757/34949388-976fdbd2-f9d5-11e7-9fff-05a5a515699a.png)

I'm not too sure how many actual experienced business owners are working within the code & workflow of this plugin, but.......

❗️ 🤔 ❗️ 🤔 ❗️ 🤔  **THAT DOESN'T MAKE SENSE**

So, we've got the ```ability``` to find USPS "Service Packages", right ❓ Yep ✅  
Which means we **"do"** have access to ```pull``` the actual USPS packages into WooCommerce Services and display it to the store owner......
..... yet instead of displaying the **ACTUAL** packages that are available for ```USPS First Class``` mail, WooCommerce Services is simply prompts for the packages of USPS Priority Mail Boxes & USPS Priority Mail Express Boxes?

See how that doesn't make much pragmatic, business, and practical sense?

In the **RATE** area, it should prompt for the RATE
Then, once the store owners get over to the **PACKAGE** area, it should prompt for the PACKAGE

Make sense?

**Comment by jeffstieler** [comment]
Hello @BurlesonBrad,

Thank you for your feedback and putting so much detail into the issue you've created. We value user feedback!

I agree that the relationship between Rates and Packages in WooCommerce Services is not immediately clear. For example - Flat Rate packages are not included in the "Packages" screen because they're tied to Flat Rate services. Selecting a Flat Rate service enables the corresponding package automatically (and transparently).

We're pulling the service names directly from the USPS rating API. That's why it appears that packaging is part of the "Rates" step for First-Class Mail - USPS distinguishes between "envelopes" and "large envelopes" for rating purposes.

_(These aren't bespoke envelopes you can get from the USPS but rather envelopes that meet certain criteria: https://www.usps.com/ship/preparing-domestic-shipments.htm)_

Since "stamped letter" and "large envelope" are really functions of size, I believe we can collapse them into a single service with a name like "First-Class Mail - Envelope". I think the same works for "postcards" and "large postcards". We can also probably combine "parcel" and "package service".

Does this sound like a step in the right direction?
