### ISSUE TITLE
Items do not pack into boxes as expected

### ISSUE THREAD

**Issue by stephhjacq** [Automattic/woocommerce-services#1298]
933608-zen

Set up a box that should fit several of the product, but a new box is added for each additional item. The item is a sheet of labels, barely thicker than a sheet of paper. You should be able to fit a stack of them in the box. 
Using USPS First Class Package with custom box. Suspect box packing issue.

Product: 
![http://cld.wthms.co/FvrLyy](http://cld.wthms.co/FvrLyy+)
Full Image: http://cld.wthms.co/FvrLyy+

Package: 
![http://cld.wthms.co/aJMIP2](http://cld.wthms.co/aJMIP2+)
Full Image: http://cld.wthms.co/aJMIP2+

Box added for second item:
![http://cld.wthms.co/Qz8WTR](http://cld.wthms.co/Qz8WTR+)
Full Image: http://cld.wthms.co/Qz8WTR+

Labelled high to tie in with work on box packing issue.

**Comment by keninbassart** [comment]
Have another one with the same issue

942417-zen

When shipping items that go in a flat rate box, it's using one box per item even though multiple items fit. Because of this, it's pulling the Priority Mail Rate as the cheapest rate instead of the Flat Rat Box Rate when there are more than one of an item. 

Example:  

![bag of coffee dimensions](http://cld.wthms.co/EB26hi+)

Rate Settings:

![ratesettings](http://cld.wthms.co/q1uTdL+)

Package Settings:

![package](http://cld.wthms.co/OQDvh+)

Pulled Rates:

![rates](http://cld.wthms.co/h7ZXyh+)

**Comment by keninbassart** [comment]
Also appears this may be related:  https://github.com/Automattic/woocommerce-services/issues/1293

**Comment by jeffstieler** [comment]
@stephhjacq @keninbassart

We've just deployed a fix to our server that should resolve this problem. There's no need to update the WooCommerce Services plugin - the issue should just be corrected.

Please let us know if the problem persists. Thanks!

**Comment by keninbassart** [comment]
Thanks @jeffstieler I updated the customers and asked them to test.
