### ISSUE TITLE
When entering custom boxes, merchant should be warned if no rates will be available for the custom box

### ISSUE THREAD

**Issue by v18** [Automattic/woocommerce-services#1397]
# Steps to repro:
1. Create a custom box where the length + girth are more than 108 inches, for example:
```
"length":32,
"width":10,
"height":32,
```
This box will not be able to be shipped with any rates except USPS retail ground.
2. Select any rates except retail ground:
<img width="553" alt="retail-ground" src="https://user-images.githubusercontent.com/11487924/39895381-015cd4bc-5478-11e8-839c-85d7091891a8.png">
3. Create a product that is too large to fit into any boxes except the one you created in step 1
4. Add this product to cart, and see that no checkout rates are available

# What should happen:
We should warn the merchant when they've entered a box that cannot be used during checkout.

# More info
First reported in #1390

**Comment by jeffstieler** [comment]
> We should warn the merchant when they've entered a box that cannot be used during checkout.

Where should this happen - in the "add package" modal? We'll need to do this check for all live rates carriers (USPS and Canada Post for now).

_cc @kellychoffman for design input_

**Comment by kellychoffman** [comment]
Interesting problem. This will only be useful if we can tell them which package to use. Is that possible? 

Thinking:
1. When the custom package gets created, a warning pops up on save that mentions that the current services enabled can't ship this package and lists one or more services that will support said package. 
2. When a service gets removed that is the only way to ship a package, a warning should pop up that mentions that package x can no longer be shipped because service y was removed. (Thinking removal of services is less frequent of a thing.) Do we track this?

**Comment by laurendavissmith** [comment]
Closing since we arent focusing on live rates at the moment
