### ISSUE TITLE
Order editing issue

### ISSUE THREAD

**Issue by sanhet** [Automattic/woocommerce-services#1499]
When a large order is placed (usually consisting of over 90 products) and it needs to be edited to remove out of stock items and change prices by admin, I encounter the following problem.
The first 50 or so products in the order can be edited, however after a certain point in the list of products on the order, any changes done do not get applied. To solve this problem, I reverse the order of products on the order so that the bottom products come to the top, which I can then edit, however, this is very impractical.

**Comment by v18** [comment]
Hi @sanhet, thanks for reporting the issue :) Can you share a screenshot of the page where you're editing the order?

**Comment by sanhet** [comment]
![image](https://user-images.githubusercontent.com/42907855/44979762-d7b01900-af65-11e8-9f74-8b211dd397d2.png)

**Comment by v18** [comment]
Hi @sanhet - thanks! Do you have the plugin 'WooCommerce Services' installed on your site?

If yes, does this issue still happen when WooCommerce Services is deactivated? (You can deactivate it to check, and then reactivate it back again.)

**Comment by sanhet** [comment]
Hi,
   I had not installed Woocommerce Services plugin in the first place. 
Thanks

**Comment by v18** [comment]
Ah, I see @sanhet :) This is a place to report WooCommerce Services plugin issues, that's why I was asking.

It looks like this issue is related to WooCommerce directly. I recommend getting in touch with support from this page: https://woocommerce.com/contact-us/

Or if you are unable to contact support, and are able to consistently reproduce the issue, you can file a bug report directly with WooCommerce:
https://github.com/woocommerce/woocommerce/issues
