### ISSUE TITLE
Release 1.18.0

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-services#1553]
- [x] Prepare release notes (can use this issue to capture them)
- [x] Create the release branch and ZIP
- [x] Manual sanity testing - see #1552 
- [x] Decide if this merits a woocommerce.com blog post and write one if so
- [x] Upload to .org repository
- [ ] Post blog post

**Comment by RadoslavGeorgiev** [comment]
Raw list of all PRs (needs editing)

# WooCommerce Services 1.18.0

## Core plugin changes

- [Prevent Stripe from attempting to connect if the site is not using ssl]
(https://github.com/Automattic/woocommerce-services/pull/1527)
- [Fix crash when making proxy requests with broken Jetpack token](https://github.com/Automattic/woocommerce-services/pull/1530)
- [Remove shipping service status for non-grandfathered sites](https://github.com/Automattic/woocommerce-services/pull/1532)
- [Show admin notice for missing product dimension errors](https://github.com/Automattic/woocommerce-services/pull/1536)
- [Don't show admin notice for "unactionable" events](https://github.com/Automattic/woocommerce-services/pull/1538)
- [Removing the background of borderless buttons in hover state](https://github.com/Automattic/woocommerce-services/pull/1540)
- [Display packing log in frontend debug and on order details](https://github.com/Automattic/woocommerce-services/pull/1542)
- [Update calypso dependency to catch the update to `npm-run-all`.](https://github.com/Automattic/woocommerce-services/pull/1545)
- [Changing the shipping_phone field to avoid conflicts](https://github.com/Automattic/woocommerce-services/pull/1546)
- [Replace alarming Stripe settings notice with helpful text](https://github.com/Automattic/woocommerce-services/pull/1547)
- [Fix missing button colors with latest Calypso](https://github.com/Automattic/woocommerce-services/pull/1554)

### Pending PRs

- [Add Stripe OAuth connect action into settings](https://github.com/Automattic/woocommerce-services/pull/1513)
- [Add specificity to root selector to avoid conflicts in Calypsoified wp-admin.](https://github.com/Automattic/woocommerce-services/pull/1549)

## From Calypso

- [Store: Add a "help" link to the Tariff Number field header that points to a documentation page](https://github.com/Automattic/wp-calypso/pull/28245)
- [Store Services: Redirect user to next step upon valid address entry in the shipping label dialog](https://github.com/Automattic/wp-calypso/pull/28533)
- [Store Services Fix #1493: Convert the "Edit Address" link to a proper button](https://github.com/Automattic/wp-calypso/pull/28542)
- [Store Services: Add a "Use address as entered" when an verified address is being edited](https://github.com/Automattic/wp-calypso/pull/28593)
- [Store Services: Removing redundant commas when state is missing from an address](https://github.com/Automattic/wp-calypso/pull/28666)
- [Store Services: Handle failed shipping label downloads gracefully](https://github.com/Automattic/wp-calypso/pull/28804)
- [Decode shipping method HTML entities in label purchase rates step ](https://github.com/Automattic/wp-calypso/pull/29061)

**Comment by RadoslavGeorgiev** [comment]
We are still waiting for the following two PRs to be merged:
https://github.com/Automattic/woocommerce-services/pull/1513
https://github.com/Automattic/woocommerce-services/pull/1549

In the meantime, I think that we should proceed with testing and here is the .zip file for it:
[woocommerce-services.zip](https://github.com/Automattic/woocommerce-services/files/2652902/woocommerce-services.zip)

**Comment by DanReyLop** [comment]
> ✅ = Include in official notes

We usually "doctor" the changelogs more, so we provide only information the user can care about. For example, `Add specificity to root selector to avoid conflicts in Calypsoified wp-admin.` seems like an internal bugfix, but `Ensure compatibility with the WordPress.com eCommerce plan` can be a changelog entry.

This is my shot at the changelog for this release:

```
= 1.18.0 =
- Add compatibility with WordPress 5.0
- Add compatibility with the WordPress.com eCommerce plan
- When purchasing a shipping label, allow addresses to be entered without verification
- Make the shipping label purchase process more robust, allowing retries when the label image failed to download
- Allow connecting a Stripe account directly from the Stripe settings page
```

Thoughts? Maybe we could also add a vague "UI improvements to the shipping label address form", since you made several enhancements there.

Note: We need to mark the plugin as compatible with WP 5.0 [here](https://github.com/Automattic/woocommerce-services/blob/master/readme.txt#L5).

**Comment by RadoslavGeorgiev** [comment]
I copy-pasted the wrong emoji for #1549, it is intentionally in the "Internal Notes" section.

FYI, most entries in the list are already doctored 😆 
I have no particular claims for the list, I can make it shorter, although I will still need to add one or two more mentions, especially for the packing log. I see no reason to shorten the list though: On WordPress.org the list appears in the Development tab and for me it makes sense to include details, because then people can immediately know that a specific issue that they were facing has now been addressed.

In my opinion your list (along with a paragraph or two per item) will be suitable for a woocommerce.com blog post, if we decide to release one (have we ever done it?)

As for the version: https://github.com/Automattic/woocommerce-services/compare/release/1.18.0?expand=1

**Comment by RadoslavGeorgiev** [comment]
> The shorter it is, the better chance there is that people will actually read it. Users don't care if this release has an extra "more info" tooltip in the HS Tariff Code field, or if a link is now a button, but they may care if something that wasn't possible (or was broken) now it's possible (connect the Stripe account, allow unvalidated address), or compatibility issues (Calypsoify, WP 5.0) have been fixed.

Alright, I will doctor it and will probably follow your list/example.

> I think we've only done it when a major feature has been introduced (first plugin release, shipping labels, international shipping labels, etc). The question you have to ask is "Will this update make someone consider installing this plugin?", and I think in this case the answer is "no". People that have the plugin installed will already see the update notification, so no need to "advertise" to them.

I agree.

**Comment by RadoslavGeorgiev** [comment]
Do you like it [like this](https://github.com/Automattic/woocommerce-services/compare/release/1.18.0?expand=1#diff-eb6b6c90251ab33cee784713c451e6d8)?

**Comment by allendav** [comment]
Tests well on WP 5 for me. I also tested connecting (ala staging) to my test Stripe Connect account and that worked fine as well. Also see new text @dechov added in #1547
