### ISSUE TITLE
WCS overwrites manually entered Stripe accounts

### ISSUE THREAD

**Issue by RadoslavGeorgiev** [Automattic/woocommerce-services#1592]
[![Video](https://cdn-std.dprcdn.net/previews/FP41Cf.preview_medium.jpg)](https://cld.wthms.co/FP41Cf)

During the on-boarding wizard of WooCommerce users can choose to enable the Stripe payment gateway. When enabled, they can also enter an email address that will be used to register a Stripe account for them, and to auto-configure the extension to work with that account.

For this to work, the wizard will also install and activate WooCommerce Services. At the end of the OBW users are prompted to connect their site/store to Jetpack, but that is an optional step.

### The issue

If someone skips the Jetpack step after choosing to have an account created for them, the account will neither be created, nor connected. Although this could be considered a bug by itself, there is not much we can do to fix it. WCS requires an active Jetpack connection in order to use Automattic's services to register the Stripe account.

### The symptom

When both WCS & Jetpack are active, and Jetpack gets conneced, WCS will step up, create the account, and save it locally. This could be fine as long as no Stripe account was entered yet. However, __if there is one, it will get overwritten__, and that can create a lot of trouble for our merchants, as @ryandonsullivan explained in [their tweet](https://twitter.com/ryandonsullivan/status/1108921326348046336).

### Proposed solution

Make sure that no account has already been entering before proceeding with https://github.com/Automattic/woocommerce-services/blob/master/woocommerce-services.php#L537

**Comment by ryandonsullivan** [comment]
Thank you @RadoslavGeorgiev.

I believe this is exactly what happened in our case. The initial onboarding was aborted because Jetpack wasn't needed. At that step in the process everything that was necessary to run the shopping cart we knew how to manage/configure so didn't bother continuing with the Jetpack setup.

But then later on Jetpack was activated/connected and the Stripe payment gateway settings were overwritten just as you demonstrated. I'm glad this is getting addressed.

Is Jetpack a dependency of WooCommerce/WooCommerce Services?  I know this is a larger change and probably outside the scope of this bug but I'd ask if the Jetpack setup/activation/configuration belongs in the WooCommerce onboarding at all.

Thanks again for your timely response to this and helping to validate the bug.

**Comment by RadoslavGeorgiev** [comment]
> Is Jetpack a dependency of WooCommerce/WooCommerce Services? I know this is a larger change and probably outside the scope of this bug but I'd ask if the Jetpack setup/activation/configuration belongs in the WooCommerce onboarding at all.

You can say that WooCommerce Services is to WooCommerce what Jetpack is to WordPress. Jetpack brings WordPress.com's cloud-based solutions to self-hosted WordPress, and WooCommerce Services brings WordPress.com's cloud-based solutions to WooCommerce.

Because of this connection, WooCommerce services utilizes the connection between the site and WP.com that is/was created by Jetpack. If you were to install WooCommerce Services outside of the on-boarding wizard, you would be prompted to also install Jetpack, making this dependency more obvious.

@v18 Do you think we should modify the WooCommerce OBW in order to make it clear that WCS depends on the Jetpack connection if somebody tries to skip that step?

**Comment by v18** [comment]
> Do you think we should modify the WooCommerce OBW in order to make it clear that WCS depends on the Jetpack connection if somebody tries to skip that step?

Yes!

I don't have a good immediate plan to do this. I opened an issue with a proposed solution:

https://github.com/Automattic/woocommerce-services/issues/1595
