### ISSUE TITLE
Extend WP_Error to send errors to our server

### ISSUE THREAD

**Issue by jkudish** [Automattic/woocommerce-services#16]
Just an idea, but it'd be cool if we could mine errors produced by the client to understand common problems and help debug users with issues.

What if we extended `WP_Error` with a custom `WC_Connect_Error` and synced errors to our server. In pseudo-code something like this:

``` php
class WC_Connect_Error extends WP_Error() {

  function __construct( $error_code, $error_message, $error_data ) {
    parent::__construct( $error_code, $error_message, $error_data );
    if ( Jetpack_Client && Jetpack_Client::remote_request exist ) {
      // send an authenticated request if possible so we can get the site ID
      Jetpack_Client::remote_request( 'https://api.woocommerce.com/errors', array(
        'method' => 'PUT',
        'body' => array(
          'error_code' => $error_code,
          'error_message' => $error_message,
          'error_data' => $error_data
        )
      ) );
    } else {
      // Jetpack has problems if this is happening but let's still record it
      wp_remote_post( $the_same_args_as_above );
    }
    }

}
```

Thoughts? @allendav @jeffstieler @nabsul

**Comment by jeffstieler** [comment]
Let's spike on this to see what's possible, and if there are any examples to learn from within Automattic.

**Comment by DanReyLop** [comment]
cc/ @jeffstieler @nabsul @v18 @marcinbot I thought we could have the discussion here in the open. If anyone opposes I'll delete this and do a P2 instead. (Sorry Joey, I guess you'll want to Unsubscribe from this).

I've done a fair bit of research about this. We have 2 kind of client errors we want to log to our server: Javascript errors and PHP errors.

## Javascript Errors
For the Javascript errors, the best example we can follow is the one of `wp-calypso`. When the app is loaded, a handler is attached [[#](https://github.com/Automattic/wp-calypso/blob/master/client/boot/index.js#L218) > [#](https://github.com/Automattic/wp-calypso/blob/master/client/lib/catch-js-errors/index.js#L37)] to `window.onerror`. That handler collects contextual information about the error and sends it to a [WPCOM REST endpoint](https://github.com/Automattic/wp-calypso/blob/master/client/lib/catch-js-errors/index.js#L120).
To get information about the error, they're using [TraceKit](https://github.com/csnover/TraceKit), which is a library that tries very hard to get as much info as possible about an error (mainly, the stacktrace). Since the errors on all the browsers we support have already support for the `Error.prototype.stack` property [[#](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/stack#Browser_compatibility)], we shouldn't need that.

Notes:
* **Sourcemaps**: Since our code is minified, the stacktrace will be meaningless without a sourcemap. Tweaking the `webpack` config, we can easily generate sourcemaps, and with those sourcemaps "translate" the stack traces. We should store these sourcemaps somewhere as part of every client release process.
* **3rd party errors**: Calypso doesn't have this problem because the whole page will be running Calypso and Calypso only. But we can't just flood our server with all the errors caught by `window.onerror`. Since we have the stacktrace on the client, we should be able to filter and send only the errors that have `woocommerce-services.js` somewhere in the stack.

## PHP errors

I've seen how Jetpack does it, and I came empty. The only ~weird~ interesting thing they do about errors is [here](https://github.com/Automattic/jetpack/blob/master/class.jetpack.php#L2401): they store them in `Jetpack::state('php_errors')`, but I haven't found that value read anywhere else.

In PHP you can set an [error handler](http://www.php.net/manual/en/function.set-error-handler.php), similar to `window.onerror` in JS. That error handler will receive mostly all errors (except really `FATAL` ones like parsing errors) and we can do whatever we want with them. The error includes the file and the line, so we can filter and process only the errors originated in `woocommerce-services.php` or `classes/*.php`. If that function returns `FALSE`, the default error handling goes on, so it's pretty safe to use.

## Proposed solution

### JS client
Custom `window.onerror` handler:
* If `error.stack.includes('woocommerce-services.js')`:
  * Send error info to `/rest/connect/js-error` (endpoint name is not real)

No need for `TraceKit` since all modern browsers support stacktraces.

Also, we should a general-purpose `logError` function that does just the "Send error to `/rest/connect/js-error`" part, so we can manually log caught exceptions or failed Promises.

### PHP client
Custom `set_error_handler` handler:
* If `file in ["woocommerce-services.php", "classes/*.php"]`:
  * Send the error to an endpoint on the WCS server
* In any case, return `FALSE` to trigger the default error handling functionality.

Same as with JS, we should have the "Send error to the WCS server" logic separated in a function so it can be called from caught exceptions and `is_wp_error` checks. Also, the REST endpoint `/js-error` will need to call that function too for re-transmitting the JS errors from the client to our server.

The errors sent to the server must have, at the very least, this info:
* Plugin version (to match the stacktrace with a sourcemap)
* Type (JS or PHP)

### WCS server
New endpoint, called `/js-errors` (for example).
* If `receivedError.type === "js"`:
  * `realStack = translateStack( receivedError.pluginVersion, receivedError.stack )`
  * `logInLogstash(receivedError, realStack)`

New endpoint, called `/admin/upload-sourcemap/{pluginVersion}`:
* Receives the sourcemap data for the given plugin version, stores it in MySQL

Maybe we could commit the sourcemaps to the server instead of hot-loading them into MySQL? That would mean that for every client release we should to a synchronized server release too. I'm leaning a bit  towards the MySQL option, but I'm not commited to it yet.

**Comment by jkudish** [comment]
Seems like a solid plan 💯 😄

**Comment by jeffstieler** [comment]
First off - excellent work on this @DanReyLop! 🏆 🎉 

> **Sourcemaps:** Since our code is minified, the stacktrace will be meaningless without a sourcemap. Tweaking the webpack config, we can easily generate sourcemaps, and with those sourcemaps "translate" the stack traces. We should store these sourcemaps somewhere as part of every client release process.

Have you found a sourcemap module for Node that will work with what we can generate using Webpack?

> Maybe we could commit the sourcemaps to the server instead of hot-loading them into MySQL?

👍 

> That would mean that for every client release we should to a synchronized server release too. I'm leaning a bit towards the MySQL option, but I'm not committed to it yet.

Perhaps we can write the `translateStack()` to fail gracefully if the sourcemap can't be found for the version of the client reporting an error. That way we minimize the damage caused by any delay in deploying new sourcemaps.

**Comment by DanReyLop** [comment]
> Have you found a sourcemap module for Node that will work with what we can generate using Webpack?

The "default" library to handle sourcemaps is [Mozilla's source-map](https://github.com/mozilla/source-map/). Webpack-generated sourcemaps are standard, so we don't need any special tooling. That library is pretty low-level, so we will need some RegExp sorcery to parse a stacktrace. I haven't looked at it much, but we should be able to copy&paste parts of [this library](https://github.com/novocaine/sourcemapped-stacktrace).

> Perhaps we can write the translateStack() to fail gracefully if the sourcemap can't be found for the version of the client reporting an error. That way we minimize the damage caused by any delay in deploying new sourcemaps.

Sure, we should make the error endpoint to fail gracefully, but there's no reason to have any delay when uploading the sourcemaps. We can just compile the client ZIP, upload the sourcemaps to the server, release the server and *then* release the client.

It looks like you prefer the "commit the sourcemaps" option instead of the MySQL one. It seems to be a bit simpler (one less endpoint, one less MySQL table), the only downsides are that it requires a server release foreach client release, and that the sourcemaps folder will probably be **huge** after a few releases. I don't have any hard numbers to back this claim, though.

**Comment by laurendavissmith** [comment]
Closed as we're going to take a wait and see approach on this one to see if it's something we want to spend time building out or possibly using an external vendor for this
