### ISSUE TITLE
Do not allow USPS Labels ship date on Sundays

### ISSUE THREAD

**Issue by RiaanKnoetze** [Automattic/woocommerce-services#1622]
2060362-zen

Customer reports the following:

> After printing the labels, on Friday, I noticed the ship date was on Sunday. USPS doesn't even run on Sunday and most USPS shipping software won't even allow ship dates that fall on Sundays.

This is illustrated by the following screenshot:

![https://cld.wthms.co/1YW5RC](https://cld.wthms.co/1YW5RC+)
Full Image: https://cld.wthms.co/1YW5RC+

Should [WooCommerce Services](https://woocommerce.com/products/shipping/?aff=10486&cid=1131038) run automatic checks for labels to **not** be dated on a Sunday or is this more dependent on the Shipping Calculator plugin in use?

**Comment by v18** [comment]
@RiaanKnoetze did this user run into any issues when trying to ship the package with this label?

**Comment by RiaanKnoetze** [comment]
@v18 - I'm no USPS pro here but the customer did mention the following:

> But this issue with the ship date must be fixed because USPS is very strict about correct ship dates.

@shaunkuschel - Do you have any additional insight on USPS running on Sundays in the US? I don't have that background information on how shipping in the US works :)

**Comment by shaunkuschel** [comment]
I know USPS has delivered packages on Sundays [in the past](https://about.usps.com/news/electronic-press-kits/holidaynews/2014/pdf/hc2014_faqs.pdf) and their rate calculator allows for Sunday selections, even though it isn't always/normally an option.

**Comment by RiaanKnoetze** [comment]
@shaunkuschel - So that's for delivery; What about pickup/sending - Does USPS allow for that on a Sunday?

**Comment by v18** [comment]
So far we have found that being a bit off doesn't affect whether USPS will accept the shipment.

I'll change to to "bug" so we can keep track of it and fix.

**Comment by DanReyLop** [comment]
> But this issue with the ship date must be fixed because **USPS is very strict about correct ship dates**.

They really aren't. We're received less than a handful of complaints in the 2+ years we've been selling labels. The general consensus is that the date doesn't really matter but a very little percentage of post office clerks will follow the rules to the letter and give you a stern look.

Right now we're just puting the label date as "tomorrow", whether it's Saturday, Sunday, or a bank holiday. We're exploring changing that to "today" since sending a package before its "ship date" may raise more eyebrows. We're also exploring adding a date selector to the label purchase modal, but personally I wouldn't complicate the UI if it's not a real problem.

**Comment by shaunkuschel** [comment]
I'm not sure what the customer is referring to when they say:

> most USPS shipping software won't even allow ship dates that fall on Sundays.

However, the rate calculator on USPS.com has a date picker for the 'What's the Date you plan to mail the item?' selection, which does allow weekend days to be selected. However, in all the quick tests I did, that didn't change the price or delivery date- likely because you can drop off packages in the big blue mailboxes on any day you'd like, but they won't be processed/shipped until the post office is actually open.

![](https://cld.wthms.co/C9IikT+)
(Link to screenshot: https://cld.wthms.co/C9IikT+)

**Comment by allendav** [comment]
Closing this issue. Some post offices allow Sunday drop off of parcels.
