### ISSUE TITLE
Spike: Determine the remaining effort to implement FedEx

### ISSUE THREAD

**Issue by laurendavissmith** [Automattic/woocommerce-services#1641]
We would like to implement FedEx as an additional carrier and it appears there has been some work done around this already. This spike is to determine what's remaining to complete the implementation.

Deliverable: p2 on wcship

**Comment by bor0** [comment]
From what I checked, I saw there was already some code in both `woocommerce-connect-server` and `woocommerce-services`. For the connect server, I did a diff against `lib/shipping/fedex` and `lib/shipping/usps` and it seems some parts of the code are very different. For example, boxes will be different (this is expected) but the logic for getting rates seems to be also different.

I jumped on #team-hydra with these findings and got a few answers which I think suffice for this spike.

@DanReyLop noted that the logic is very different because for USPS, the raw USPS XML API is used for checkout rates, and EasyPost for label rates & label purchase. For FedEx, it was decided to use EasyPost for everything, and that complicated the checkout rates part a lot [#](https://a8c.slack.com/archives/CNXMMQBDW/p1575297640204400?thread_ts=1575294483.204000&cid=CNXMMQBDW)

Since the rates/purchase logic is same as USPS, there shouldn't be a lot more work as @marcinbot noted. Mostly copy-pasting the logic from USPS and tweaking it to FedEx (I have a stashed and untested commit for this).

For the checkout rates we would need a separate spike.

**Comment by bor0** [comment]
More details around https://a8c.slack.com/archives/CAKN301C3/p1575395605488100?thread_ts=1575382863.479800&cid=CAKN301C3

**Comment by c-shultz** [comment]
>Mostly copy-pasting the logic from USPS and tweaking it to FedEx (I have a stashed and untested commit for this).

@bor0, if you still have those can you push them up into a branch so we can get a general idea of what's involved?

**Comment by bor0** [comment]
@c-shultz I don't have them. In general the current implementation should work, but some missing parts should be copy-pasted from USPS. For example:

```
bor0@boro:~/dev/woocommerce-connect-server/lib/shipping$ diff --recursive fedex/ usps/ --exclude=service-data.js --exclude=preset-boxes.js --exclude=service-groups.js --exclude=preset-boxes-groups.js
```

Will show some missing logic in FedEx that already is implemented in USPS. One example:

```
> /**
>  * Sometimes EasyPost returns "mock" tracking numbers. To identify and discard those,
>  * we must check if the tracking number is valid according to USPS formats.
>  * I've got the list of formats from https://www.trackingmore.com/usps-tracking.html
>  *
>  * @param {String} tracking Tracking number
>  * @returns {boolean} Whether the tracking number is valid
>  */
> const isValidTracking = ( tracking = '' ) => {
> 	tracking = tracking.toUpperCase().split( ' ' ).join( '' );
> 	return _.some( [
> 		/^\d{22}$/, // This is the most common, so put it first to return early
> 		/^[RAEDTVCLGU][A-Z]\d{9}US$/,
> 		/^M\d{9}$/,
> 		/^\d{10}$/,
> 		/^\d{20}$/,
> 		/^\d{26}$/,
> 		/^\d{28}$/,
> 		/^\d{30}$/,
> 	], ( re ) => re.test( tracking ) );
```

Do we need to copy/paste that tho? I am not sure.

My idea was to first get some response from EasyPost and then adjust the code if needed. The issue was that we could not test EasyPost because it did not return FedEx data at all. See this gist: https://gist.github.com/bor0/3930f745dc6bac698a66f92123545ae1
