### ISSUE TITLE
Remove async behavior from create label button

### ISSUE THREAD

**Issue by laurendavissmith** [Automattic/woocommerce-services#1671]
In #1664 we found out that the button is tied to an async data load which caused us to have to implement a loading indicator.

At first glance it appears that this data _may_ not be necessary to trigger that click if we clean up some of the code. This story is to investigate having the button available immediately instead of waiting for the data.

If the solution is relatively simple lets go ahead and implement it, if it requires a large amount of code to be refactored it should be discussed at the dev roundtable prior to implementation

**Comment by bor0** [comment]
The button has multiple render conditions:

1. [areLabelsEnabled](https://github.com/Automattic/woocommerce-services/blob/da04c1d/client/apps/shipping-label/view-wrapper-label.js#L90) which depends on the API call to `http://localhost:8080/wordpress/wp-json/wc/v1/connect/account/settings` <img width="762" alt="Screen Shot 2019-10-10 at 11 15 43" src="https://user-images.githubusercontent.com/1620929/66555697-5efb9300-eb4f-11e9-8f66-30a542e3113c.png">
    - Further, I checked what it really means for labels to be `enabled`. It seems this is [hardcoded](https://github.com/Automattic/woocommerce-services/blob/b3a7cb5/classes/class-wc-connect-service-settings-store.php#L55) in the backend, so it has no use for now.
2. [areLabelsFullyLoaded](https://github.com/Automattic/woocommerce-services/blob/da04c1d/client/apps/shipping-label/view-wrapper-label.js#L53-L54), which in addition to the API call above also calls `http://localhost:8080/wordpress/wp-json/wc/v1/connect/packages` and `http://localhost:8080/wordpress/wp-json/wc/v3/data/continents`

Additionally, our application does multiple calls to the same `settings` endpoint, each of which takes ~2 secs. Maybe that's why we wait so long for the button?

<img width="1304" alt="Screen Shot 2019-10-10 at 11 16 41" src="https://user-images.githubusercontent.com/1620929/66555758-79357100-eb4f-11e9-9bab-9426fb6575be.png">

In any case, I tried removing the render conditions from the button and tried clicking on it straight away. I get `Cannot read property 'origin' of undefined` which comes from [here](https://github.com/Automattic/woocommerce-services/blob/6dbd8cd/client/extensions/woocommerce/woocommerce-services/state/shipping-label/actions.js#L273). In other words, before the button is clickable we try to normalize the `origin` and `destination` address, and attempt to retrieve labels for these normalized addresses. The form opens, but I am not sure if anything breaks. Gist [here](https://gist.github.com/bor0/89959c6a0fc3145d3107055965d77bf2).

**Comment by bor0** [comment]
Roundtable: We close this issue as latest `develop` has a very fancy busy indicator now.

Open another issue to investigate why we hit the API multiple times for settings/continents/packages.
