### ISSUE TITLE
E2E testing infrastructure follow-up

### ISSUE THREAD

**Issue by harriswong** [Automattic/woocommerce-services#1698]
We have a PR (https://github.com/Automattic/woocommerce-services/pull/1692) ready for end to end to end testing locally. 

Here are a list of follow up tasks for the remaining work for that PR:

- [x] `tests/e2e-tests/utils/components.js` Update `await page.waitFor( 2000 );` to wait for element to show up instead of a fixed time. `2000` sometimes is too fast for the product notice to show up and failed the test
- [x] `tests/e2e-tests/utils/flows.js` Update `const WP_ADMIN_EXISTING_ORDER_PAGE = baseUrl + '/wp-admin/post.php?post=82&action=edit';` so that the post ID is passed in instead of fixed.
- [x] Finish the shipping label tests `tests/e2e-tests/specs/admin/create-shipping-label.test.js` 
- [ ] ~Make sure travis-ci pass test using headless mode (`npm run test:e2e` runs in headless mode)~
- [ ] ~Some of "flows' might be duplicated of https://github.com/woocommerce/woocommerce/pull/24218/files, we may need to create follow up to clean this up. Depending on how we want to refactor them.~
- [ ] ~Make sure Travis runs PHPUnit on version 5.3 to 5.6~
- [ ] ~Check if we need PHP 7.3 coverage in Travis' tests~
- [ ] ~Update .travis.yml notification to team email~

**Comment by Ferdev** [comment]
Tried to run the e2e suite in my dev machine (Arch Linux + docker) resulted in several random errors in the test suite. It failed most of the time when creating the product in the `beforeAll` step: puppeteer was unable to find the "Publish" product button, even thought the button was there. I think the problem has something to do with the auto-save future of the post. If more people have problems with this, it may be worth it to ask Proton since they've been working on their e2e suite and they've probably figured out how to test this screen already.

**Comment by Ferdev** [comment]
More tasks we should strive to implement:
- [ ] Make each test case independent from the others.
- [ ] Install always the latest stable WooCommerce for travis-ci.

**Comment by Ferdev** [comment]
Closing this one in favor of all the new issues we've created off this one.
