### ISSUE TITLE
Minor display glitch when adding label

### ISSUE THREAD

**Issue by c-shultz** [Automattic/woocommerce-services#1714]
When the `Add package` button is pushed on the `Add a package` modal, the modal content very briefly disappears before the modal actually closes:

![2019-10-09 11 35 32](https://user-images.githubusercontent.com/6209518/66521807-cd354c80-eaa0-11e9-941e-e41c422ddc8d.gif)

**Comment by bor0** [comment]
Took a quick look at this. Here are some investigation details for whoever decides to tackle it next.

The [`PackageDialog`](https://github.com/Automattic/woocommerce-services/blob/04dc8d6/client/extensions/woocommerce/woocommerce-services/views/packages/package-dialog.js) component (the actual modal) [renders](https://github.com/Automattic/woocommerce-services/blob/04dc8d6/client/extensions/woocommerce/woocommerce-services/views/packages/package-dialog.js#L184) the [`PredefinedPackages`](https://github.com/Automattic/woocommerce-services/blob/6dbd8cd/client/extensions/woocommerce/woocommerce-services/views/packages/predefined-packages.js) component. Pretty standard. The problem is when we call [`dismissModal` within `PackageDialog`](https://github.com/Automattic/woocommerce-services/blob/04dc8d6/client/extensions/woocommerce/woocommerce-services/views/packages/package-dialog.js#L118). Specifically resetting the [currently editing packages](https://github.com/Automattic/woocommerce-services/blob/7275278/client/extensions/woocommerce/woocommerce-services/state/packages/reducer.js#L74). It also sets `showModal` to false, but before it gets to that, `PredefinedPackages` [rerenders](https://github.com/Automattic/woocommerce-services/blob/6dbd8cd/client/extensions/woocommerce/woocommerce-services/views/packages/predefined-packages.js#L93) an empty list.
