### ISSUE TITLE
No shipping rates with 500 error when used with international shipping and no credit card setup

### ISSUE THREAD

**Issue by harriswong** [Automattic/woocommerce-services#1768]
### Environment:
- Jurassic Ninja env
- Wordpress.com and remove the credit card **<-- this seems to be the reason why it fails**

### Steps to Reproduce:

1. Create a shipping label with Origin Address somewhere in United States
2. Destination address as `275 Yorkland Road, Toronto, Ontario, M2J 0B4, Canada`
3. Go to package, use "Custom Packaging" with some dimensions, I used 5w, 2l, 4.2h. And weight of 2oz
4. Custom form show up and fill the required fields
5. Click "Save customs form" and shipping rate spins
6. Result with "Error.... Internal server error"
![image](https://user-images.githubusercontent.com/572862/67873533-32f18300-faf9-11e9-9901-f46512d461b3.png)

**Comment by c-shultz** [comment]
This one has an interesting root cause. For international destinations, it needs the merchant's name for the customs form. It tries to get a name by checking billingdaddy for the name on their credit card. Since there may be no credit card with our new flow, this errors out. Here's the relevant code in the connect server:
https://github.com/Automattic/woocommerce-connect-server/blob/9ec2d60cd2fcbbeadac10beb6aafd5197807f038/lib/shipping/easypost-client/index.js#L140-L149

There's a comment there with why this was done:
```php
// The merchant name must appear in the Customs form. Instead of relying on the "name" of the "origin address" fieldset,
// which can be anything from the business name to "Supervisor", "Shop manager" etc, get the name from the credit card we have
// on file, it has better chances of being someone's actual legal name.
```

One possible solution would be to add a name field to the customs section, so they're required to provide that (maybe we could prefill it from the origin address in case that's a useful value?):
<img width="2058" alt="image" src="https://user-images.githubusercontent.com/6209518/68057993-f66a8680-fcb4-11e9-9103-f07d75e796d6.png">

@aleftick / @laurendavissmith , what do you think about the above solution? This will require extension changes and connect server changes to implement.

**Comment by aleftick** [comment]
Interesting. This would apply only to new users shipping internationally; that likely a rare case but never the less it's a scenario we need to cater to. 

Just an idea, could, in this case, hide the name field and just pull it from the credit card filled once we get the card from the user?. The user won't get to review it but it's a compromise we can live with.

**Comment by c-shultz** [comment]
It looks like we need the correct customs info before requesting rates. To request rates, we need to generate a 'shipment' that includes all the package info (including customs info), and send that to easy post to get rates.

Maybe we could add the legal name input box in the location I show above if and only if they have not added a credit card before?

**Comment by bor0** [comment]
@c-shultz does it still error after https://github.com/Automattic/woocommerce-connect-server/issues/1316? I found this issue while working on the test cases.

**Comment by c-shultz** [comment]
@bor0,

I'm still getting the 500 error with that PR. For some reason, I'm getting an error from the billing daddy server, so https://github.com/Automattic/woocommerce-connect-server/pull/1319 adds on to your change by using the origin name if it catches an error.
