### ISSUE TITLE
Make E2E suite  work in Travis

### ISSUE THREAD

**Issue by Ferdev** [Automattic/woocommerce-services#1834]
Currently the e2e suite in the branch `new/e2e-test-infrastructure` doesn't pass in Travis.

Original issue: #1698

**Comment by superdav42** [comment]
I got the test passing in travis. Mostly fixed the non e2e tests. The e2e test is marked as passing but is really failing. 
I think we need more discussion and I don't fully understand the next steps for getting the e2e test passing properly.
I suggest we merge in new/e2e-test-infrastructure even without it fully working so it does not get to stale and work on improving e2e tests in a new issue.

**Comment by c-shultz** [comment]
>I think we need more discussion and I don't fully understand the next steps for getting the e2e test passing properly.
I suggest we merge in new/e2e-test-infrastructure even without it fully working so it does not get to stale and work on improving e2e tests in a new issue.

Good call. This one has just been dragging on since our meetup. Can you talk about and/or demo the current state of the E2E tests at the dev roundtable? We can decide on next steps and add issues.

**Comment by c-shultz** [comment]
I'm closing this now that @superdav42 merged the original branch, and I've opened some more specific issues:
- https://github.com/Automattic/woocommerce-services/issues/1898
- https://github.com/Automattic/woocommerce-services/issues/1897
- https://github.com/Automattic/woocommerce-services/issues/1896
