### ISSUE TITLE
Hosting optimizations cause issues when assets are versioned using query arguments.

### ISSUE THREAD

**Issue by budzanowski** [Automattic/woocommerce-services#1856]
We should discuss/spike assets versioning system that alters assets filename/url . This way we should avoid all the issues that are coming from caching and other optimizations.

**Comment by superdav42** [comment]
Some notes and possible solutions.

Webpack has [several options](https://webpack.js.org/configuration/output/#outputfilename) for generating the filename that is outputted.

Simplest solution add the version number to the filename with a function like:
```js
filename: () => {
	return '[name]-' + process.env.npm_package_version + '.js';
},
```
The only downside with this approach is we must remember to **update the plugin version in package.json**. Something that I am not in the habit of doing but we could add a check to woorelease to make sure it's done.

Other solution are possible.
##Read from a manifest file##
Most of the time `[hash]` is used to generate a unique filename based on the contents of the file. This is tricky to use in a WordPress environment because WordPress will need a way to determine the hash key to know which filename to enqueue. There are a few plugins that can be used to do this. Most common is [Webpack Manifest Plugin](https://github.com/danethurber/webpack-manifest-plugin) which generates a json file which will map the asset name to the generated filename. WordPress could parse this manifest file and enqueue the correct filename.

##Use the Gutenberg Plugin##
Gutenberg seems to have developed it's [own plugin](https://github.com/WordPress/gutenberg/tree/master/packages/dependency-extraction-webpack-plugin) that generates an `.asset.php` file similar to the manifest json which contains the correct filename to enqueue. There [usage of it](https://github.com/WordPress/gutenberg/blob/4c178b8402bce5f8c41b3e1b677e66b92707a328/lib/client-assets.php#L252) seems a little complicated and possibly overkill for our needs.

**Comment by superdav42** [comment]
So my recommended solution is https://github.com/Automattic/woocommerce-services/pull/1861 Only caveat being we keep packages.json up-to-date. So far we have done a good job of this but I'd feel better if we added a check to woorelease.
