### ISSUE TITLE
No link to update card in Settings when card is declined (WCShip modal)

### ISSUE THREAD

**Issue by elizaan36** [Automattic/woocommerce-services#1874]
**Describe the problem**
When going through the flow to print a label, I had an expired card saved in my account. The error message from the WCShip modal showed "The transaction was declined. Please try another card." but there wasn't a clear way to take action on that. The place to update your credit card is very hard to find, so this is a cumbersome task for merchants who expect to quickly print a shipping label.

Here's the WCShip modal with the error message that the card was declined and no clear path forward.

<img width="1573" alt="Screen Shot 2020-01-17 at 12 02 10 PM" src="https://user-images.githubusercontent.com/5121465/72752200-3724be00-3b87-11ea-8728-d04e06c9b688.png">

The place to edit the credit card used for shipping labels is here: **WooCommerce > Settings > Shipping > WooCommerce Services** (Including 3 subnav menus that are hard to spot for a new user - or anyone really.)

<img width="1451" alt="Screen Shot 2020-01-20 at 1 13 39 PM" src="https://user-images.githubusercontent.com/5121465/72752002-b796ef00-3b86-11ea-9eb9-d2e1fcd62087.png">

**Describe the solution you'd like**
I shared this with the WCShip team today and @laurendavissmith suggested a quick win would be to add a link in that error message. So "Please try another card." would take you to the relevant settings area (shown above) to add a card or switch to a different one.

In the future we could think about alternative solutions that would surface the WCShip settings to make them more accessible from the WCShip flow.

**Comment by laurendavissmith** [comment]
as a note we also need to make sure that button becomes reenabled so a user can buy without relaunching the modal after adding a new card

**Comment by budzanowski** [comment]
There is no easy way to do this.
In short: we don't know what the error actually is. WCS only gets the error string passed from BillingDaddy through the connect server. There can be multiple different error messages related to payments and they are passed through internationalization functions so we actually can't even relly on the string itself.

The long versions:
When one requests a label purchase the WCS sends the request to the connect server. The connect server then starts processing the request, EasyPost and BillingDaddy are involved. The WCS plugin does not wait for a response immediately but starts a polling function that checks the purchase status every second. This means that the connect server is doing its thing and WCS just checks every second if the purchase is done or not. The polling stops when the status from the connect server is either success or failure.  When the connect server finalizes the purchase ( either OK or Failure ) it stores that information in the database. This part is what stops us from having a clean solution because the connect server does not store the detailed status from BillingDaddy. It **only stores the error message string**! When WCS during polling asks about the status, the message string and a generic payment error code is the only thing it gets. BIllingDaddys status is lost. 

If we would like a clean solution we would need to pass the error code. But for that to happen we would need to store the error code. For that to happen we need to update the DB schema 😨 
 
The none clean solution is to always display the link to CC settings in case of any possible CC errors. Even in cases when the link is not that useful. For example, I have seen  `Please try again later.` error messages that do not suggest changing CCs or validating any information. I do think that in this case, a link to CC settings is still OK. There may be others ( we would need to dig through BillingDaddy codebase to know all ).

@elizaan36, @laurendavissmith, @c-shultz thoughts?

**Comment by budzanowski** [comment]
The #1882 addresses the Issue in the generic form of having all purchase error notices with a link to the settings page. If this form is acceptable please adjust copy if necessary:
![image](https://user-images.githubusercontent.com/17271089/73172733-ffc48d00-4103-11ea-843e-d0254fc638c8.png)

Note: we can't change how the link is presented inside the notice without a significant time investment. There is a notices framework in the code that has 0 flexibility in terms of how the link can be shaped. We can only adjust txt.

**Comment by elizaan36** [comment]
This looks great. One question - are there any errors that wouldn't be because of the credit card? If so, to cover more possible errors I'd use `Go to settings` or `Go to payment settings` for the link.

**Comment by budzanowski** [comment]
There are other errors that spawn notices that are not credit card related, but only payment related errors get this notice. If we will identify other places we can add links to the relevant places - but that will be something else code-wise. The part of code modified in the PR handles only payment errors.
