### ISSUE TITLE
Cannot select package after removing only item from only package

### ISSUE THREAD

**Issue by c-shultz** [Automattic/woocommerce-services#1876]
Cannot select package after removing only item from only package:

![2020-01-21 07 41 50](https://user-images.githubusercontent.com/6209518/72819176-a4852d00-3c21-11ea-984b-871f142d8cf2.gif)

The only way to resolve this is to refresh the order page.

**Comment by harriswong** [comment]
There seems to be a warning in console when all items are removed.
```
backend.js:6 Warning: unstable_flushDiscreteUpdates: Cannot flush updates when React is already rendering.
    in PackageInfo (created by Localized(PackageInfo))
    in Localized(PackageInfo) (created by Connect(Localized(PackageInfo)))
    in Connect(Localized(PackageInfo)) (created by PackagesStep)
    in div (created by PackagesStep)
    in div (created by FoldableCard)
    in div (created by Card)
    in Card (created by CompactCard)
    in CompactCard (created by FoldableCard)
    in FoldableCard (created by Localized(FoldableCard))
    in Localized(FoldableCard) (created by StepContainer)
    in StepContainer (created by Localized(StepContainer))
    in Localized(StepContainer) (created by PackagesStep)
    in PackagesStep (created by Localized(PackagesStep))
    in Localized(PackagesStep) (created by Connect(Localized(PackagesStep)))
    in Connect(Localized(PackagesStep)) (created by LabelPurchaseModal)
    in div (created by LabelPurchaseModal)
    in div (created by LabelPurchaseModal)
    in div (created by LabelPurchaseModal)
    in div (created by DialogBase)
    in div (created by ModalPortal)
    in div (created by ModalPortal)
    in ModalPortal (created by Modal)
    in Modal (created by DialogBase)
    in DialogBase (created by Dialog)
    in MomentProvider (created by Connect(MomentProvider))
    in Connect(MomentProvider)
    in Provider
```

**Comment by harriswong** [comment]
Currently, if we remove the items from the package, we can't add them back. The best we could do is display something like this:
![image](https://user-images.githubusercontent.com/572862/72945869-66c7f780-3d3a-11ea-87d3-59e388a96dc4.png)

The area under "Packages to be Shipped" will be empty, and "Items to fulfilled" would also be empty. The users won't be able to do anything beside new package. Creating new package simply adds a "Custom package" to the drop down, not creating a packaging in the list. 

I think this modal will be more useful if we can have some ways to display items that are not part of any package, and allow user to add items to new packages.

Once we have the above, then we can fix this issue.

**Comment by elizaan36** [comment]
As an interim solution until we can organize this area a bit better, we could add an item for unpackaged items to the list on the left. [Click through the prototype here](https://www.figma.com/proto/okUIuzENoQNGMX1e4ppC8x/Orders%E2%9A%94%EF%B8%8EWCShip?node-id=135%3A19723&viewport=598%2C40%2C0.25&scaling=min-zoom). 

![fix for packaging WCShip](https://user-images.githubusercontent.com/5121465/73001354-f071d680-3dc7-11ea-8f19-fd2dadc95f4a.gif)


1. When an item is removed from a package, it's added to a new "Unpackaged items" area. 
2. From the "Unpackaged items" list, you can choose to "Add new package with this item/these items"
3. Clicking that will create a new package with the items and the "Unpackaged items" area is removed.

[Here's the Slack thread.](https://a8c.slack.com/archives/CKNC7KACA/p1579730764018300)

**Comment by harriswong** [comment]
We had a discussion at the dev round table this morning and we decided to move ahead with the design above.

Currently, the "Add package" inside "Package 2" adds a new "Package" option into "Custom package" in the drop down, it doesn’t actually move item into any packages.
![image](https://user-images.githubusercontent.com/572862/73027703-29727100-3df1-11ea-8012-aae7ca00bd6b.png)

This "Add a package" modal looks like this, it will just add to the custom package drop down. So it has the dimension and weight.
![image](https://user-images.githubusercontent.com/572862/73027784-4c9d2080-3df1-11ea-9a5f-69b60757d8a6.png)

In the gif above,  the "Add new package with this item" opens up the same modal as "Add package", but the "Add new package with this item" actually add items and create "Package 2" on the side.

Instead of popup the modal upon clicking "Add new package with the item", maybe we can add these 2 fields back and it will create a "Package 2" on the side? Something like this:
![image](https://user-images.githubusercontent.com/572862/73027904-984fca00-3df1-11ea-9323-e68a4222d4b6.png)

**Comment by elizaan36** [comment]
> Instead of popup the modal upon clicking "Add new package with the item", maybe we can add these 2 fields back and it will create a "Package 2" on the side

From what I understand, when "Add new package with the item" is clicked, the "Unpackaged items" would change to "Package 2" and those two fields would appear. That seems reasonable to me, just a couple questions. 

- Is there any reason why we can't use this suggested pattern for consistency with the regular "Add package" link, rather than opening the modal? Looks like there are a lot more options in the modal - would merchants need to choose from those details when creating the new package?
- Do we have defaults for the last package selected so we could pre-fill those fields?

Pinging @laurendavissmith and @aleftick here too, since adding this "Unpackaged items" area would allow for partial fulfillment. To keep the status automation simple though, we could maintain the "Processing" status until *all* items in the order have been fulfilled.

**Comment by harriswong** [comment]
If I understand the figma click through correctly; when "Add new package with the item" is clicked, the "Add package" dialog pops up. Then in this dialog, clicking "Add package" will create "Package 2"?

And this popup dialog will share the same consistency as the "Add package" link. 

There is no reason why we can't use the suggested pattern for UI consistency. As long as we are fine with them having different behaviours.

1. This "Add package" link (in the screenshot below) opens up a dialog to allow merchant to create a custom package option. It does not add item into package. 
![image](https://user-images.githubusercontent.com/572862/73092428-d4d70080-3e99-11ea-8883-5efda281cee2.png)

2. This "Add new package with this item" link (in screenshot below) opens up the same dialog, but adds an item to a package to the left column. It doesn't create a "custom package"
![image](https://user-images.githubusercontent.com/572862/73092683-431bc300-3e9a-11ea-8dd9-5e88d86ae046.png)

I wanted to point out that these 2 dialog do 2 different things. And if we are okay with them using the same dialog, then we can build that. This may sound confusing so please feel free to ping me on slack if you would like me to demo what I meant.

**Comment by c-shultz** [comment]
Marking this as blocked. @aleftick plans to look into the history of the `Remove from package` to determine next steps. One possible path forward is remove that functionality until we can prioritize addressing partial fulfillment more holistically.

**Comment by harriswong** [comment]
PR: https://github.com/Automattic/woocommerce-services/pull/1886

**Comment by aleftick** [comment]
@c-shultz found when and why we added `Remove from package`. 🙇 It was in issue #1811. 

I see how that originated and the solution makes sense. However, it gets us into partial orders. That scenario also existed prior to the Penguin release and didn’t seem to come up in customer feedback. It’s a pretty edge case.

I feel comfortable for **us removing the `Remove from package` option**. WCShip won’t formally handle partial orders until we have a more holistic approach. Something we will tackle in due-time. 

However, **merchants can still buy a label for their partial orders**. It's a workaround. They can override the package weight to reflect what they're actually shipping and print a label accordingly.

**Comment by aleftick** [comment]
> PR: #1886

@harriswong - It's a good solution however it creates a few challenges for us:
1. We don't have a partially fulfilled status or a way to track what is left to fulfill the next time they come to print a label for the remaining items. That might confuse merchants.
2. More importantly, we want to add a new capability that isn't really compatible with this fix. We want to help automate the flow by having an opt-out option to mark the order fulfilled and email the shipping confirmation to the shopper. This fix with that new feature would likely create confusion. 

Hence we need to look at partial order and partial fulfilment in a more holistic way.
