### ISSUE TITLE
EU tax rates not correct?

### ISSUE THREAD

**Issue by yukikatayama** [Automattic/woocommerce-services#1891]
With Automate taxes enabled, and setting my nexus to the UK, when checking out with any country in the EU, the tax rate is at 20%. I couldn't find a comprehensive list with TaxJar, but Avalara shows that the standard rates for these countries range between 15% - 27%:  https://www.avalara.com/vatlive/en/vat-rates/european-vat-rates.html

In testing, debug for say, Denmark, shows 20% when it should be 25%

```
01-28-2020 @ 16:18:33 - {"tax_rate_country":"DK","tax_rate_state":false,"tax_rate_name":" Tax","tax_rate_priority":1,"tax_rate_compound":false,"tax_rate_shipping":1,"tax_rate":20,"tax_rate_class":""} (WCS Tax)
```

**Comment by anant1811** [comment]
2658909-zen for sending an update when this is resolved.

**Comment by damiannep** [comment]
Also 2963047-zen for sending an update when issue resolved.

**Comment by yukikatayama** [comment]
2947864-zen reporting similar issue.

Looks like tax charges the same percentage as if shipping to the nexus country, when it is going to a different country in EU.

**Comment by dani-elo** [comment]
3552845-zen for sending an update when this is resolved.
User is selling Digital Goods in the EU.

I have suggested [following this document that explains how to configure that manually](https://docs.woocommerce.com/document/setting-up-eu-vat-rates-for-digital-products/) or Taxamo as workarounds.

**Comment by bborman22** [comment]
It seems that this issue has been addressed by TaxJar and the proper rates were returned in my testing. I've included some screenshots of most of the countries mentioned just to confirm. This was with a store located in the UK and shipping to the countries selected during checkout. I will close this ticket for now as it seems to have been an issue on the TaxJar side that is resolved, but we can reopen this if the same issue is still occurring.

![Croatia](https://user-images.githubusercontent.com/68524302/110835491-dd8cc080-826c-11eb-843b-be9bdfc52360.png)
![Denmark](https://user-images.githubusercontent.com/68524302/110835493-dd8cc080-826c-11eb-9a85-769ff86b022d.png)
![Finland](https://user-images.githubusercontent.com/68524302/110835495-de255700-826c-11eb-983c-90031a5a16c4.png)
![Germany](https://user-images.githubusercontent.com/68524302/110835496-de255700-826c-11eb-9528-ce30b1ea521e.png)
![Spain](https://user-images.githubusercontent.com/68524302/110835498-de255700-826c-11eb-99bf-d52e09b3e4b8.png)

**Comment by billrobbins** [comment]
I ran into another instance of this.  The customer's store is in Finland and they noticed that when shipping to Germany, the returned rate is 24%.  Germany's VAT rate is 19% but Finland's is 24%.  

Whatever I change the store's nexus location to, that's the rate that is returned instead of the customer's shipping location.  

France's VAT is 20%
![France](https://cdn-std.droplr.net/files/acc_705319/kE4N0e)
(Link to screenshot:  https://d.pr/i/kE4N0e)

Finland's VAT is 24%
![Finland](https://cdn-std.droplr.net/files/acc_705319/rrBh1D)
(Link to screenshot:  https://d.pr/i/rrBh1D)

3869438-zen

**Comment by FangedParakeet** [comment]
I recently tried to replicate this, but did not manage to do so reliably. Ultimately, I was only able to replicate the results that @bborman22 exhibited a little further above. I can confirm that there is definitely no longer any issue with TaxJar, as the response from TaxJar definitely returns with the correct rates, when supplied the correct parameters. 

I suspect that there is either some unusual caching afoot or some location issue that is causing a customer's location to default to the store base. 

It might be a bit late to go back to the store owner to allow us access to their site, but @billrobbins if you were able to replicate this consistently on a test site, could you please point us in its direction or give us a few more setup details that could help us get to the bottom of this one?

**Comment by frosso** [comment]
@billrobbins thanks for the details!
I also made some tests and I can confirm that the tax rate being charged is consistent with the tax rate of the store's base address:
- [IT > IT - 22%](https://d.pr/i/lleeSn)
- [IT > DE - 22%](https://d.pr/i/RmfDf0)
- [FR > FR - 20%](https://d.pr/i/jPuuHK)
- [FR > DE - 20%](https://d.pr/i/WJTSCN)

I checked the API response from TaxJar and it seems consistent with what I see at checkout.

In the EU when merchants are selling B2C, the rate of VAT charged depends on how much the merchant is selling within the EU.

> If your business stays below €10,000 in cross-border sales of digital goods per year, throughout the EU, then you can charge the VAT rate of your home country on all those cross-border sales. Once you pass the €10,000 annual sales threshold, you must charge the VAT rate of your customer’s country.
Source: https://www.quaderno.io/resources/eu-vat-guide

A similar scenario also happened [with Brexit and the £135 consignment value](https://www.gov.uk/guidance/vat-and-overseas-goods-sold-directly-to-customers-in-the-uk).
When I inquired TaxJar about it they replied:

> Our Tax Research team is aware of the change, however; the TaxJar API will continue to calculate a simple rate multiplied by cost. Thus, the credits and thresholds will not be taken into account. At this point enhancements to the VAT calculations are not yet on the roadmap [...].
> To clarify, based on the country, we can provide a simple calculation but we don't have proper functionality for true VAT calculations (such as sourcing, non-standard rates by product category, reverse charge mechanism, input tax credit support, recoverability, etc.) since much of VAT depends on who the user is (B2B or B2C) and registration status of that customer.

So it sounds like for countries part of the European Union, the VAT charges depend on how much the merchant is selling (and who the merchant is selling to). But TaxJar doesn't have a feature that allows us to submit information about the tax thresholds. The plugin is however still reporting the values submitted by TaxJar.

Let me know if you have any other questions, otherwise feel free to close the ticket!
