### ISSUE TITLE
Help merchants use pickup for eligible labels

### ISSUE THREAD

**Issue by c-shultz** [Automattic/woocommerce-services#1905]
For #1885, we plan to display to merchants when a service qualifies for free pickup. We should additionally help merchants know how they can use free pick up with the carrier.

**Comment by elizaan36** [comment]
We could include "Schedule pickup" as one of the action items in the Shipment Tracking panel. Here's a quick walkthrough: https://share.getcloudapp.com/JruWNzO8

Screenshot:
<img width="1434" alt="Screen Shot 2020-02-18 at 1 53 43 PM" src="https://user-images.githubusercontent.com/5121465/74772702-2040bc80-5256-11ea-9465-9c08408c6131.png">

Note that I have this panel in the left column, but the menu would behave the same in the right column. 

Speaking of, as part of this issue can we adjust the behavior of the kebab menu so that it doesn't rotate at all upon clicking?

**Comment by c-shultz** [comment]
That looks great! I'm assuming we're linking to something like this page for USPS? https://tools.usps.com/schedule-pickup-steps.htm

Would it be good to include an external link icon so they know it's going to jump off the page? 
<img width="62" alt="image" src="https://user-images.githubusercontent.com/6209518/74801052-47b17c80-528a-11ea-9b9f-9f444ae02618.png">


>Speaking of, as part of this issue can we adjust the behavior of the kebab menu so that it doesn't rotate at all upon clicking?

Yeah, that should be straightforward. So it should just stay horizontal all the time?

**Comment by elizaan36** [comment]
Awesome, and yes good call. I added the external link icon and turned the kebab into meatballs. 😸 

The horizontal ellipses is my preference, but I was trying to be consistent with an area of wc-admin. I thought about it, and these contextual menus within individual panels can have a different orientation to the app bar. It won't be implemented for a while anyway, so we'll just keep an eye on if it becomes confusing.

<img width="1438" alt="Screen Shot 2020-02-19 at 9 10 30 AM" src="https://user-images.githubusercontent.com/5121465/74847577-f7710380-52f7-11ea-96b3-9aabf9fe0aa7.png">

[Here's the Figma](https://www.figma.com/file/fcebyhNqZ9RhkFUzPHAtUG/WCS?node-id=43%3A4929)

**Comment by superdav42** [comment]
@elizaan36 
I noticed you removed the print icon and the other icons from the dropdown in the design. Is this intentional?
Also regarding the ellipses rotation change and other design changes to match wc-admin I think we may want to try tackling these as part of a more comprehensive switch to use WordPress components instead of calypso components as it actually makes these additions more than a trivial addition.

**Comment by c-shultz** [comment]
>Also regarding the ellipses rotation change and other design changes to match wc-admin I think we may want to try tackling these as part of a more comprehensive switch to use WordPress components instead of calypso components as it actually makes these additions more than a trivial addition.

Thanks for calling that out, @superdav42. It looks like my assumption that that would be a quick one was wrong.

My vote is to leave it as is for now.

Some background for @elizaan36: This code used to be a part of the Calypso repository, so many UI components are Calypso components. As we can prioritize it, we want to start converting over to `@wordpress/components`.

**Comment by elizaan36** [comment]
> I noticed you removed the print icon and the other icons from the dropdown in the design. Is this intentional?
