### ISSUE TITLE
"You save" tooltip does not always line up

### ISSUE THREAD

**Issue by c-shultz** [Automattic/woocommerce-services#1906]
For very wide or very narrow browser windows, the "you save" tooltip is not appearing the right spot on mouseover

<img width="645" alt="image" src="https://user-images.githubusercontent.com/6209518/73974371-170c3300-48d9-11ea-9df0-3561dd26556a.png">

**Comment by superdav42** [comment]
There's a bug in the Calypso Tooltip component that appears fixed in the latest master branch. But we would need to update our git submodule to take advantage of that. I tried briefly and at appears to not be a easy process and there could be many breaking changes. 

During rountable we decided to try using the worpress tooltip component to try to fix this problem. We want to start transitioning to wordpress components and this is a good time to do so.

**Comment by c-shultz** [comment]
Should this be moved over to ready to review now, @superdav42?
