### ISSUE TITLE
"Ready for shipment" text not updated after label is created

### ISSUE THREAD

**Issue by c-shultz** [Automattic/woocommerce-services#1907]
Currently, when a label is created, you still see "# item(s) ready for shipment":
<img width="230" alt="image" src="https://user-images.githubusercontent.com/6209518/73974841-f395b800-48d9-11ea-92bb-823161499ad3.png">

The design calls for this to be updated to "# item(s) have been shipped" after a label is created:
<img width="193" alt="image" src="https://user-images.githubusercontent.com/6209518/73974987-453e4280-48da-11ea-8113-93c1a85746f7.png">

**Comment by c-shultz** [comment]
@aleftick, after looking at this one, I wonder if reporting the items as "shipped" is the wrong wording. We can trigger this message after a label has been printed, but that doesn't necessarily mean that the items are "shipped." What do you think?

**Comment by aleftick** [comment]
Agree. Prior to printing the label, we have `1 item is ready for shipment` which also a bit inaccurate. 

Maybe we should have `1 item is ready for fulfilment` and `1 item has been fulfiled`. Is `fulfiled` a term that is familiar to an average user?

**Comment by c-shultz** [comment]
'Fulfill' seems to me like it could be less clear to some users. I like that `1 item is ready for shipment` makes it really clear that the banner is for shipping.

I wonder about leaving the _before_ message as is and then changing the _after_ message to something about the label(s), like `1 shipping label created`

**Comment by elizaan36** [comment]
> I wonder about leaving the before message as is and then changing the after message to something about the label(s), like `1 shipping label created`

How about `1 item was fulfilled on [date]`/`X items were fulfilled on [date]`

This reflects our thinking that once the shipping label is created the order is essentially fulfilled, and that the merchant has picked and packed the items. This copy could be shown whether they've chosen to mark the order as complete or not, and whether it's actually In Transit or Delivered.

Then in the order notes people can see more detailed progress via shipment tracking.

**Comment by elizaan36** [comment]
But yeah, then we may want to change the before message to:
`1 item is ready for fulfillment`/`X items are ready for fulfillment`"

It's a tough one because I like referring directly to the shipment. 

FWIW, in most of the sessions I've had with merchants and Woo Experts everyone has understood the term fulfillment. I was curious about whether people were familiar with that term and intentionally included it as part of the interview questions during orders research.

**Comment by c-shultz** [comment]
>FWIW, in most of the sessions I've had with merchants and Woo Experts everyone has understood the term fulfillment. I was curious about whether people were familiar with that term and intentionally included it as part of the interview questions during orders research.

That's good enough for me then. My preference for "shipment" certainly wasn't based on any research 😁

**Comment by elizaan36** [comment]
Tbh, I like "shipment" too, but like you said it gets tricky after the label is printed because we don't necessarily know *when* the package was shipped unless we want to pull in information from shipment tracking. As-is, the shipment tracking status can provide that detail in the order notes and we can keep the header more generic based on our knowledge that the label was printed.

Here's the copy I have in the designs for now:
<img width="492" alt="Screen Shot 2020-02-14 at 11 00 01 AM" src="https://user-images.githubusercontent.com/5121465/74551699-45ad8d80-4f19-11ea-88be-95ac1dee43ac.png">

`"1 item is ready to be fulfilled"`/`"X items are ready to be fulfilled"`
Minor change from the copy in my comment above, which was "...ready for fulfillment" to make the language more clear and actionable.

<img width="491" alt="Screen Shot 2020-02-14 at 11 00 10 AM" src="https://user-images.githubusercontent.com/5121465/74551722-50682280-4f19-11ea-9267-2ccc39ea1ef8.png">

`"1 item was fulfilled on [date]"`/`"X items were fulfilled on [date]"`
