### ISSUE TITLE
@wordpress/components Tooltips not displayed if WC Admin is active

### ISSUE THREAD

**Issue by Ferdev** [Automattic/woocommerce-services#1951]
The recently added tooltips in `develop` don't work if the WC Admin plugin is installed and active.

**Comment by superdav42** [comment]
Did some investigating and the reason this is happening is because the version of `@wordpress/components` in wc-admin is newer than the version in WCS. `8.5.0` vs  `7.0.8`
The breaking change is in the stylesheet which set all tooltips to opacity:0 until they are fully loaded. https://github.com/WordPress/gutenberg/commit/a2d0227676eb904f45eb81f5b435e938ed2ae389
Because both wc-admin and wcs are loaded on the same page the styles from both are loaded and applied globally while the JS components are both loaded but do not conflict with each other thanks to the way webpack packages them. 
Probably the best solution is for WCS to upgrade `@wordpress/components` but we should explore methods to avoid conflicts like this in the future.
