### ISSUE TITLE
WP 5.4 Testing

### ISSUE THREAD

**Issue by c-shultz** [Automattic/woocommerce-services#1952]
Test with WP 5.4 and bump WP tested version.
Changes: https://make.wordpress.org/core/tag/5-4+dev-notes/

**Comment by harriswong** [comment]
Tested on jurassic ninja with latest WCS. Purchased a label and the transaction shows on credit card. 
Clicked refund and the status changed. 
I haven't received the refund yet but I am guessing it takes a couple of days to process. 

The order, label purchasing, order tracking, refund flow works fine otherwise.

**Comment by c-shultz** [comment]
Looks good! We'll get the version tested bumped [when we release](https://github.com/Automattic/woocommerce-services/issues/1958).
