### ISSUE TITLE
"Mark this order as complete and notify the customer" option doesn't stay checked anymore

### ISSUE THREAD

**Issue by anant1811** [Automattic/woocommerce-services#2124]
Previously, if you check the "Mark this order as complete and notify the customer" option for one order, it would stay checked so when you open the print shipping label window for other orders, you wouldn't need to re-select the "Mark this order as complete and notify the customer" option. 
![https://d.pr/i/dPYnkj](https://d.pr/i/dPYnkj+) 
Full Size: https://d.pr/i/dPYnkj

That doesn't happen anymore though, and it defaults to unchecked state for each order. 

Was this intended to prevent users from accidently completing the orders(and notifying the customers)? 

Affected tickets:
3191664-zen

**Comment by mouligreenlaw** [comment]
Another here:
3241492-zen

**Comment by c-shultz** [comment]
Thanks for raising the concerns here! It looks like we have some differing requirements from different merchants, based on the feedback we got here: https://github.com/Automattic/woocommerce-services/issues/2005

Our plan for that is to start remembering if the checkbox has been checked or not and use that selection as the default the next time they open an order. I'll close this in favor of #2005 since both concerns should be addressed by this.

**Comment by LuckyHerbals** [comment]
I am trying to default to mark order complete and notify the customer when postage is purchased/printed. How can this be resolved? We really liked that feature before the latest update..
