### ISSUE TITLE
fix: label purchase change checkboxes and price

### ISSUE THREAD

**Issue by frosso** [Automattic/woocommerce-services#2185]
## Description

By checking the one of the checkboxes underneath a label ("Adult signature required", "Signature required") the price changes.
Selecting a checkbox, changing the shipping service and selecting the another service with the same service availability maintains the service as "checked". However, the price is not correctly reflecting the information.
![2020-09-16 08 46 47](https://user-images.githubusercontent.com/273592/93346453-9fe93680-f7f9-11ea-920a-050e06160ab3.gif)

## Acceptance criteria
- The price reflects the information based on the services being checked

**Comment by senff** [comment]
Came across this in #25076632-HC.

Additional note: when you go through the purchase of the label, it actually doesn't charge you for the signature option at all.  In a test we did, it would only charge the amount on the right (so that would be $7.94 in the example above) and not the full amount ($10.59).

CC: @jrick1229

**Comment by tijosh** [comment]
3419899-zen

**Comment by anant1811** [comment]
Also reported in 3434366-zen

**Comment by tijosh** [comment]
Also reported in 7974539-hc

**Comment by senff** [comment]
Also reported in 25237113-HC

**Comment by senff** [comment]
Also reported in 23364984-HC

**Comment by jkampmeier83** [comment]
Please fix! This is a critical issue for us. Is there a funding option to help prioritize bugs like this?

**Comment by c-shultz** [comment]
We're bumping this up to critical priority and we'll plan on addressing it as soon we can in our next scheduled patch release.

**Comment by melindahelt** [comment]
3476207-zen

**Comment by tommyshellberg** [comment]
Looks like this was a regression from this commit and line:

https://github.com/Automattic/woocommerce-services/commit/e56282496359932c1a9156759abe588e79f14e88#diff-e887c50e5d70e9b03b502e230e6985709e604b0ed995a0e33335eacfe2addfddR57

We changed the ShippingRates component's `onRateUpdate()` function signature from two to three parameters(added carrier_id) but the ShippingRate child component's callback function to `onRateUpdate()` was only passing two, which made the `carrier_id` value "signature_required" and the `signature_required` value `undefined`.

The fix is to pass the carrier_id in the ShippingRate child component when calling `onRateUpdate()`.
