### ISSUE TITLE
Display subscription usage in wp-admin

### ISSUE THREAD

**Issue by c-shultz** [Automattic/woocommerce-services#2257]
Merchants should be able to see their subscription usage in wp-admin ~in the WooCommerce.com extensions list:~
[removed previous design screenshot that adds usage data in WooCommerce Extensions screen]

**Usage should be displayed in WCShip settings area in new "Shipping method" card:**
![image](https://user-images.githubusercontent.com/6209518/101380868-e8e5df80-386a-11eb-8c5c-21d6770d7a47.png)

The data for this will be dependent on the subscriptions endpoint: https://github.com/Automattic/woocommerce-connect-server/issues/1615 which is progress but we can start on this prior to that merging

**Comment by c-shultz** [comment]
After some discussions, we're going to re-think where this should be displayed, so I'm going to mark this as blocked pending further design discussion

**Comment by harriswong** [comment]
> We'll need to determine if there's a good way to hook into these entries to add this data.

Adding some notes to this.

I don't think there is a good way to hook data in unless we add a new hook. The subscription is pulled from [here](https://github.com/woocommerce/woocommerce/blob/master/includes/admin/helper/class-wc-helper.php#L115). We will notice that there are no hooks all the way down to [line 349](https://github.com/woocommerce/woocommerce/blob/36108a2c83b2243b02c3fc3795cd72ae75e59b4b/includes/admin/helper/class-wc-helper.php#L349). In woo core, we can ask to add a new hook right after line 346 `self::_filter( $subscriptions, self::get_current_filter() );`. This hook will allow us to provide custom messages to the existing template, [somewhere after the "Using 1 out of 1 site available" text](https://github.com/woocommerce/woocommerce/blob/36108a2c83b2243b02c3fc3795cd72ae75e59b4b/includes/admin/helper/views/html-main.php#L83-L102). 

Assume we have the hook above added, WCS will also have to find the correct product so that it can display the proper usage based on the subscriptions endpoint. The subscription end point will need to return some identifier that we can use to find the right product, ie `product_key`, `product_id`, etc. 
![image](https://user-images.githubusercontent.com/572862/100030476-da022600-2db0-11eb-90ce-3399a3279b5d.png)

**Comment by c-shultz** [comment]
Updated with new design from @elizaan36 that puts the usage info a new card

**Comment by brezocordero** [comment]
@c-shultz What is expected to happen when the user clicks on the button `Manage` on the subscription list item?
Go to `wp-admin/admin.php?page=wc-addons&section=helper`? To `WooCommerce.com`? Something else?

**Comment by c-shultz** [comment]
It looks like Manage should go to: https://woocommerce.com/my-account/my-subscriptions/
