### ISSUE TITLE
Adding USPS label API request to woocommerce server?

### ISSUE THREAD

**Issue by asuh** [Automattic/woocommerce-services#2302]
After some reading, I think this issue belongs in the [private connect server repo](https://github.com/Automattic/woocommerce-connect-server/) that doesn't appear open to the public.

Is there any documentation about what's happening on the server api.woocommerce.com? I want to see if there was a way to add a new request to the API called `HoldForManifest`, which is available in USPS APIs to allow use of the SCAN API.

If this is the wrong place, let me know if there's a more appropriate repository to make this request or PR. Thanks!

**Comment by Ferdev** [comment]
Hey @asuh!

Thanks for the bug report! Could you please elaborate on what you would like to be able to achieve? If you could detail the full use case, that would be awesome.

**Comment by c-shultz** [comment]
@asuh,

We have SCAN support [on the ideas board](https://ideas.woocommerce.com/forums/133476-woocommerce/suggestions/37802947-usps-shipment-confirmation-acceptance-notice-scan). We take these ideas and the votes into account when making decisions about the product road map.

You are correct about this requiring modifications to api.woocommerce.com (along with UI enhancements in the plugin to utilize the new functionality).

I'll close this out since the need is being tracked on the ideas board, but thanks so much for your feedback about this.

**Comment by asuh** [comment]
Okay, thanks for the confirmation. This is why I was approaching this request differently, just asking for a small API change. Without it, I can't even look to getting a third-party plugin built to extend WooCommerce Services without going around the api.woocommerce.com to use the SCAN API.

As you can see in that idea board thread, there's multiple people who are desperate to get this implemented ASAP. The lack of any support from your side means we have to go with third-party USPS plugin solutions which aren't always as good as this plugin.
