### ISSUE TITLE
fix: focus is stolen from checkout input fields on error

### ISSUE THREAD

**Issue by frosso** [Automattic/woocommerce-services#2335]
## Description

See discussion here: https://github.com/Automattic/woocommerce-services/pull/2310#issuecomment-780554304

The Tax integration can display error messages at checkout. e.g.: on invalid zip.
When an error is rendered, the focus is stolen from the active input.

This is troublesome if the user at checkout is not using the browser's autocomplete or is not fast enough to edit the problematic field (esp. on mobile).

To reproduce:
- Enable automated taxes
- Enter a valid address
- Change the ZIP code to `99999`
- Try changing the ZIP code, one digit at a time, slowly
- Focus is stolen from the input every time.

This behavior does not occur without the plugin enabled. However, the focus-stealing behavior might be part of WooCommerce Core.
I would categorize this as an accessibility issue.

**Comment by dustinparker** [comment]
Hey @frosso,

WC core has a timeout after each `keydown` event in the fields which then triggers a checkout update. That update process then triggers our [TaxJar request validation method](https://github.com/Automattic/woocommerce-services/blob/94a2100ebbcf31efc20064c1d0622516d1b2663d/classes/class-wc-connect-taxjar-integration.php#L1242). The TaxJar address validation method has [a condition](https://github.com/Automattic/woocommerce-services/blob/94a2100ebbcf31efc20064c1d0622516d1b2663d/classes/class-wc-connect-taxjar-integration.php#L1265-L1269) (for US addresses only) that returns an error if the zipcode is not a valid US zipcode. See below:

```		
if ( 'US' === $json['to_country'] && ! WC_Validation::is_postcode( $json['to_zip'], $json['to_country'] ) ) {
    $this->_error( 'API request is stopped. Country destination is set to US but the zip code has incorrect format.' );

    return false;
}
```

Since US zipcodes have to be at least 5 numbers long, we could change the condition to the following so that the TaxJar postcode validation doesn't happen before 5 numbers have been entered:

```		
if ( 'US' === $json['to_country'] && ! empty( $json['to_zip'] ) && 5 <= strlen( $json['to_zip'] ) && ! WC_Validation::is_postcode( $json['to_zip'], $json['to_country'] ) ) {
    $this->_error( 'API request is stopped. Country destination is set to US but the zip code has incorrect format.' );

    return false;
}
```

I've tested this and it makes the validation a bit less annoying. WC core still validates the zipcode when you click "checkout", so if a customer were to enter a 3 digit code and try to checkout, WC core would still stop the process and show the invalid zipcode error.

Do you have any thoughts/concerns/suggestions regarding this solution?

**Comment by frosso** [comment]
@dustinparker I like your idea! Let's move forward with that!
