### ISSUE TITLE
Incompatibility with WC 3.0.0 despite "WC requires at least" header

### ISSUE THREAD

**Issue by waclawjacek** [Automattic/woocommerce-services#2403]
Version `1.25.10` of WCS&T is marked as compatible with WooCommerce ≥ 3.0.0: `WC requires at least: 3.0.0`.

In the `WC_Connect_TaxJar_Integration` class, WCS&T is using the `WC_Countries::get_base_address()` method that was introduced in WC `3.1.1` though:

```php
/**
 * Get the base address (first line) for the store.
 *
 * @since 3.1.1
 * @return string
 */
public function get_base_address() {
	$base_address = get_option( 'woocommerce_store_address', '' );
	return apply_filters( 'woocommerce_countries_base_address', $base_address );
}
```

This results in a fatal error when trying to use the plugin with WC 3.0.0:

`Fatal error: Uncaught Error: Call to undefined method WC_Countries::get_base_address() in /var/www/html/wp-content/plugins/woocommerce-services/classes/class-wc-connect-taxjar-integration.php:287`

This should be replaced with a 3.0.0-compatible method or the required version number should be increased.

**Comment by iyut** [comment]
I will close this issue as I checked the current WC Services header and found that the requirement has been increased : `* WC requires at least: 3.5.5` by [this PR](https://github.com/Automattic/woocommerce-services/pull/2421) and make this issue not relevant anymore. Please feel free to re-open if someone think otherwise.
