### ISSUE TITLE
Tax not calculated for Flat Rate Shipping when Default Customer Location is Shop Address

### ISSUE THREAD

**Issue by jessy-p** [Automattic/woocommerce-services#2426]
**Describe the bug**
When the Default Customer location is set to Shop Address, and the customer has not entered any shipping address, tax is not calculated for Flat Rate Shipping.
This is more obvious in stores where both Flat Rate Shipping and Local Pickup is set up because when you switch between the shipping methods on the cart page, the tax is calculated for Local Pickup but displays as 0 for Flat Rate Shipping.

**To Reproduce**
1. Setup WooCommerce Shipping & Tax, enable automated Taxes
2. Setup two Shipping methods - Flat Rate Shipping and Local Pickup
3. "Default Customer Location" is set to "Shop Address" in **Settings > General**
4. As a new user on the store, add an item to Cart.
5. On the cart page, switch the shipping method using the radio button - Tax is calculated and displayed when Local Pickup is selected. When Flat Rate Shipping is selected, tax is 0.
6. This issue persists until the user enters his full shipping address on the Checkout page.

**Expected behavior**
Tax should be calculated and displayed correctly for every shipping method.  

**Affected Tickets**
3980159-zen

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only the extension is active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by jessy-p** [comment]
This is what I believe is happening:

- When Flat Rate Shipping is selected, the shipping address defaults to the state and country of the Store. (but not zip). As the zip is empty, API call is not made and Tax is  shown as 0
- When Local Pickup is selected, the shipping address defaults to the entire address of the store (including zip) so the API call is made and Tax is calculated.

**Comment by senff** [comment]
I believe this is expected.  With Automated Taxes, tax is only applied when the shipping address' state is the same as the store address's state, OR if they select Local Pickup:

<img width="1960" alt="local" src="https://user-images.githubusercontent.com/1710669/119042982-89960a80-b986-11eb-9afd-8f9c46080e63.png">

When someone from out of state places an order, they will not be charged tax if they use Flat Rate (because the shipping address is out of state), but they **will** be charged tax if they use Local Pickup (because the item will be "shipped" to a place in the same state as the store).

Ref: 3980159-zd

**Comment by jessy-p** [comment]
Hi @senff 

That's true for out-of-state shipping. There is still a minor bug in that, for within state shipping we are showing the initial wrong tax. If the customer adds zip, it gets corrected. Screencast: https://d.pr/i/1iE7Pm

**Comment by senff** [comment]
My assumption is that until a customer fills out their state **and** zip code, the address (inc. state) isn't valid yet, and therefore considered "it could be anywhere"?  I personally don't see it as a bug, but I see what you mean.

**Comment by waclawjacek** [comment]
There probably could be a warning displayed on the cart and checkout pages instead of the `0` tax rate if tax cannot yet be calculated.

Just in case a decision to implement this is made: there was some work to display nicer shipping-related errors done in #2316 that reminds me of this issue. Error example:

<img src="https://user-images.githubusercontent.com/1759681/119189830-d52ae000-ba7c-11eb-86cc-2b575a7b8da5.png" alt="Nicer shipping error example" width="300">

**Comment by csmcneill** [comment]
Reported in 4567583-zen. Tax is not calculated on any shipments where the merchant has a tax nexus, and it is not limited to what the `Default Customer Location` setting is.

Edit: It appears as though the issue in 4567583-zen is related to custom code and is likely not affected by this issue.

**Comment by dustinparker** [comment]
Hey everyone, because this isn't really a bug and the functionality makes sense from a customer's point of view (not seeing updated tax or shipping amounts until one enters a shipping address), and because there is only one ticket that has reported this, we'd like to go ahead and close out this issue for now. Please feel free to reopen again if needed.
