### ISSUE TITLE
Currency Displaying in Country Dropdown Shipping

### ISSUE THREAD

**Issue by P0stmaster** [Automattic/woocommerce-services#2477]
I've deactivated all other plugins, yet I am having issues competing orders because the dropdown is displaying currencies rather than countries.
![sp](https://user-images.githubusercontent.com/36684450/134725584-5f64f304-6b04-42b5-81e5-bc56b654953f.png)

**Comment by P0stmaster** [comment]
Nothing?

**Comment by FangedParakeet** [comment]
Just want to add that I can replicate this issue, as long as I have the latest version of WooCommerce (5.7.1) with multi-currency enabled. I think the problems here may be related to those in #2474; as far as a cure, rolling back WooCommerce to the previous version (5.6) allows WCShip to continue to function as normal. I believe this is the only workaround currently available. Am investigating this further to see if I can see where things are going wrong...

**Comment by FangedParakeet** [comment]
# Description

All country fields inside the purchase label modal are showing incorrect values. This only occurs with latest WooCommerce 5.7.1, with multi-currency enabled. Rolling back to WC 5.6 resolves this issue. For some reason, the list of locations is now populated by currencies, since the Redux store is loading unrelated data for `locations`. 

![Redux in disarray](https://cdn-std.droplr.net/files/acc_1104206/omo7RT)
_Redux state in disarray_

# Steps to repeat

1. Setup local site with latest version of WCShip and WC 5.7.1.
2. Create a new order and attempt to purchase a label for the order.
3. Note that the country fields inside the `Origin address` and `Destination address` both contain incorrect fields--currencies instead of locations. 
4. Set `Destination address` to an international address. Note that `Origin country` field on customs form is filled with currencies containing many duplicates.
5. Cry.

# Screenshots

![Currency instead of country value](https://cdn-std.droplr.net/files/acc_1104206/CZmrFf)
_Currency shown instead of country address value_

![Origin addresses wrong](https://cdn-std.droplr.net/files/acc_1104206/zE27XN)
_Origin address country field contains currencies_

![Customs form broken](https://cdn-std.droplr.net/files/acc_1104206/eeN37U)
_Customs form Origin country dropdown contains duplicate currencies_

**Comment by luanluta** [comment]
I have another report of this here 4339918-zd-woothemes.

![https://d.pr/i/c5CpZn](https://d.pr/i/c5CpZn+) 
Link: https://d.pr/i/c5CpZn

![https://d.pr/i/U8eTtD](https://d.pr/i/U8eTtD+) 
Link: https://d.pr/i/U8eTtD

**Comment by drwpcom** [comment]
Case in 4344625-zen.
