### ISSUE TITLE
Firefox blob scheme marked as "Connection not secure"

### ISSUE THREAD

**Issue by bborman22** [Automattic/woocommerce-services#2480]
A user brought it to our attention that in Firefox, the shipping labels are opened in a new tab using the blob scheme to display the label. In doing so the page is marked with a Connect not secure warning on the URL. While there isn't any security concerns because of how the blob scheme works, it could alleviate any concerns a merchant might have when they see this warning if we're able to avoid it?

**Steps to Reproduce**
1. Start with a store with an order with a shipping label created.
2. Using Firefox, log in to the store as the merchant and go to the relevant order.
3. On the sidebar click on the label's menu and select reprint label.
4. In the modal click Print
5. This should bring up a new tab using the blob scheme.
6. The Firefox URL bar will be marked as Connection not secure.

![FF-Blob](https://user-images.githubusercontent.com/68524302/135912277-709ad8db-4823-4545-b549-6c468df6f201.png)

**Comment by csmcneill** [comment]
Initially reported in 4342617-zen.

**Comment by iyut** [comment]
@bborman22 I did some digging into the plugin code and **here is what I found** :

The plugin need to use blob in Firefox because there is some concern with the browser's PDF reader reliability based on [this comment](https://github.com/Automattic/woocommerce-services/blob/c39f7c7cbb506830beb399d0e326f19d30620100/client/extensions/woocommerce/woocommerce-services/lib/utils/pdf-support.js#L29-L30). **It seems Firefox is not stable enough to do direct printing for PDF file because of this** [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=911444). 

However, I did some testing by changing this [code](https://github.com/Automattic/woocommerce-services/blob/c39f7c7cbb506830beb399d0e326f19d30620100/client/extensions/woocommerce/woocommerce-services/lib/utils/pdf-support.js#L31) into `return 'native';` and try to print the label using Firefox (version 94) native PDF reader.
**The result** : I can print the PDF label without any issue.
**Screenshot** : [https://paste.pics/8e10a4a6fc880f66c221bb775473c96a](https://paste.pics/8e10a4a6fc880f66c221bb775473c96a)

Having said that, I'm still not sure if we can implement this changes before it's fully tested with several user. Perhaps what we can do is note this finding for future reference. Or, probably you have another suggestion?

**Comment by iyut** [comment]
@bborman22 I went ahead by adding a condition to check the firefox version in this [commit](https://github.com/Automattic/woocommerce-services/commit/e2e0d558ae4a327204c35accd1cc95b9704dad8f). What do you think of this approach?

**Comment by bborman22** [comment]
Sorry for the delay on this! That looks like a reasonable approach to the issue to me. I was curious why version 94? It looks like the linked bug was addressed in 75. Is 94 just the point we're able to test conclusively? I think that's a fine decision if so as it's not removing any functionality from anyone and gives us higher confidence.

If you're feeling up for it, would you want to create a PR for this change and we'll get it in our queue to review and merge? As part of the PR would you be able to list out any scenarios you could think of where this might not work as expected? Like would OS be a consideration for example?

**Comment by iyut** [comment]
Yeah, the decision to use version 94 is because I can only run a full test using Firefox version 94.

> If you're feeling up for it, would you want to create a PR for this change and we'll get it in our queue to review and merge? As part of the PR would you be able to list out any scenarios you could think of where this might not work as expected? Like would OS be a consideration for example?

Yes sure, I can create a PR and list out a scenario for the reviewer to test. Thanks for the advice here.
