### ISSUE TITLE
Error 500 message when updating origin address

### ISSUE THREAD

**Issue by rashedripon** [Automattic/woocommerce-services#2554]
Description of the bug:

When a merchant tries to update the origin address during creating the label it throws this error message:

`
Error validating origin address: Error: The WooCommerce Shipping & Tax server returned: Internal Server Error An internal server error occurred ( 500 )
`

How to reproduce:

- Open an order
- Click on "Create shipping label"
- Try to change or update the origin address
- Click on "Verify address"
- You will see the error message

Screenshots:

![If this image fails to load, please visit:](https://d.pr/i/XDjbCY+)
Image Link: https://d.pr/i/XDjbCY

Additional details:

One HE was able to update the origin despite getting the error message.

First reported here: 5233194-zen
Reproduced by two more HEs

**Comment by kaushikasomaiya** [comment]
5248424-zen

`/shipping/address/normalize` API endpoint returning 500 Internal Server Error on validation of certain addresses.

Example: Test, Test, Chicago, Illinois, 60647 (Use this as destination address)

Workaround - Use `Use address as entered` option.

**Comment by amElnagdy** [comment]
I got this error too and was coming here to check if it was reported. Additionally, this is the error under WooCommerce → Status → WooCommerce Shipping & Tax → Other Log

`wcc_server_error_response Error: The WooCommerce Shipping & Tax server returned: Internal Server Error An internal server error occurred ( 500 ) (WC_REST_Connect_Address_Normalization_Controller)`

**Comment by waclawjacek** [comment]
Thank you for the report! Is there any specific input that can be used to reproduce this issue? Sharing via a Slack DM is OK.

**Comment by dustinparker** [comment]
Hey everyone,

I believe this issue is related to [WC Connect Server Issue 1931](https://github.com/Automattic/woocommerce-connect-server/issues/1931) and has been fixed by [this PR](https://github.com/Automattic/woocommerce-connect-server/pull/1932). I just tested again to double check that this 500 error is no longer happening during address normalization and everything works without errors for both origin and destination.

I'd like to go ahead and close this issue out, but feel free to reopen if the issue persists.
