### ISSUE TITLE
Install Jetpack prompt returns [Object Object]

### ISSUE THREAD

**Issue by helgatheviking** [Automattic/woocommerce-services#2559]
I activated the plugin and saw the prompt at the top to install Jetpack. So I clicked the button to install Jetpack and then the button displayed this [Object Object] text where a button is meant to be.

![image](https://user-images.githubusercontent.com/507025/172875340-c240da9f-e9b5-42fa-924f-67e8b1e191d0.png)

**Comment by frosso** [comment]
I just tried to reproduce this situation with both the version of the banner that asks to "connect" and the version that asks to "install" Jetpack, but everything worked well for me after clicking the button
![Screen Shot 2022-06-09 at 9 50 27 AM](https://user-images.githubusercontent.com/273592/172877173-e9408e02-6971-4fa7-b787-5c1a2875efa0.png)
![Screen Shot 2022-06-09 at 9 50 13 AM](https://user-images.githubusercontent.com/273592/172877180-9c003e52-e76e-4c87-8ef3-69a1babd41b6.png)

It looks like this situation can happen when there's an error with the backend/AJAX call, so maybe we can look into improving the error handling.

**Comment by helgatheviking** [comment]
I installed it locally just after this and did not get the `object` thing again either.... 🤷‍♀️ 

always +1 for improved error handling :)

**Comment by iyut** [comment]
I tried to dig the plugin. And I think I found a hole that might make this issue occur:

This `if ( error && error.install && 'plugin' === error.install ) { ... }` condition in [these error handling lines](https://github.com/Automattic/woocommerce-services/blob/a0cc5c800298f149a9d83c7437fa237e1d380ac1/client/banner.js#L25-L31) might not sufficient for all error scenario such as if `error.install != 'plugin'`. If this happen, the error text will display `[Object Object]` like the author reported.

What I could propose to fix this issue is by removing the `'plugin' === error.install`. So the condition can handle more error scenario.

Or we could use this logic to handle the error : 

```
if ( error && typeof error === 'object' ) {
	// plugin install error
	errorMessage = wcs_nux_notice.translations.installError;
}
```

what do you guys think?

**Comment by iyut** [comment]
Hi, I went ahead by creating this PR #2574 . What I do in this PR is adding a condition to check if there is an error object that is not being catch yet.

Please kindly let me know if you guys have any comment on the PR.
