### ISSUE TITLE
Always allow to manually confirm/select package while printing label

### ISSUE THREAD

**Issue by AashikP** [Automattic/woocommerce-services#2570]
**Describe the bug**

When the destination address is auto verified as valid by the system it will offer you to select the package as shown below:

![https://d.pr/i/Ikv173+](https://d.pr/i/Ikv173+)

This is not the case where the destination address needs to be reviewed / we need to use suggested address. The system skips the package section and directly offers the shipping rates:

![https://d.pr/i/6Fys6w+](https://d.pr/i/6Fys6w+)

**Expected behavior**

If the destination address cannot be auto-validated / needs an update, or you need to use a suggested address, once you're done with the address, the system should still let you select the shipping package once the destination address is correctly set up.

**Steps to replicate**
1. Attempt to create an order with a valid/verified address
2. Notice that the shipping from and destination addresses are automatically validated, and you're offered to select a package
3. Now, create an order with a typo in the address
4. Notice that once you fix the address under `Destination Address` tab, you're automatically offered the shipping rates - instead of the tab to select the packaging

**Screen Recording:**

![https://d.pr/i/hB7WQF+](https://d.pr/i/hB7WQF+)

**Workaround**

* Note that you can still manually check the dropdown option and select a different package
* It is just that automatically skipping the package selection interface adds an additional click/step to the process

**Comment by harleec61** [comment]
Although there's a workaround, it requires the user to always remember to return to the package tab. Since address correct is required in 70% of our orders, this issue creates a lot of extra clicking. Also, many times the user will forget to click back in the package tab, causing an incorrect label to be printed. Then, the user has to cancel the label and redo the process. When we first purchased the plugin, this issue didn't exist, so it was broken during a software change that we hope is quick and easy to fix.

**Comment by FangedParakeet** [comment]
Added to Codeable crew's current job queue.
