### ISSUE TITLE
Regional boxes (A1, A2, B1, B2) have been discontinued by USPS.

### ISSUE THREAD

**Issue by melek** [Automattic/woocommerce-services#2627]
## The Problem

According to the USPS website, these regional boxes are discontinued as of Jan 22 2023: https://link.usps.com/2022/12/29/priority-mail-change/

In WooCommerce Shipping, these regional boxes can still be selected under 'Service Packages': 
![image](https://user-images.githubusercontent.com/220149/214150650-e3e4d71a-f0e2-42d4-82e5-3fe56a0d2dbd.png)

When selected they return a 'No Rates' error:
![image](https://user-images.githubusercontent.com/220149/214161585-2c5a7f5d-3b10-4000-92a6-55a5ab45d639.png)

## To Replicate

- Select regional box packaging under 'Service Pacakging' in **WP Admin → WooCommerce → Settings → Shipping → WooCommerce Shipping → Packaging**
- Try to select regional packaging during label purchase on the Edit Order screen (make sure the items will fit!)
- See error

## Suggested fix

- For users who have these boxes and will still use their stock of them, a notice should be displayed and they should be treated like any other custom packaging. **For a bonus**, users with these selected could have an option to add corresponding rows to their Custom Packaging automatically.
- When selected, these regional boxes should have a warning added to them in the Packaging, Add packaging, and Create a Shipping Label screens that they are discontinued and being treated as custom packaging.
- They should not be selectable if they weren't already selected - instead, a notice should appear in the Add Packaging screen for these boxes. **For a bonus**, users could click a button to auto-add these box sizes to their custom packaging list (in case they have a bunch of these).

## Context:
39564556-hc

**Comment by laurajohnsonwoo** [comment]
The suggested fix is a great idea, but I'm leaning towards just removing these packages completely from **Settings** and the **Create shipping label** screen. For merchants who still have these boxes in stock, they may use them as custom packaging until their supply is depleted as [suggested by USPS](https://faq.usps.com/s/article/Regional-Rate-Boxes), and especially if is a low number of impacted users, then removal is the preferred approach. Have some questions out to engineering via Slack and will report back! 

Decision still pending whether we have an interim error state a suggested by @melek, but here is the update that will need to be made at some point: 

The **USPS Priority Mail Regional Rate Box section** should be removed altogether from the Package details dropdown so that merchant's cannot select this option: 

<img width="619" alt="image" src="https://user-images.githubusercontent.com/112664624/214204375-df11eb21-0f5b-4158-8d62-7242fca2af9a.png">

These packages also should be removed from the **Packaging section** in WP Admin > WooCommerce > Settings > WooCommerce Shipping:  
<img width="1353" alt="image" src="https://user-images.githubusercontent.com/112664624/214205790-8757f714-1a21-44a6-9bd3-235efe1324a7.png">

**Comment by xue28** [comment]
https://wordpress.org/support/topic/no-rates-available-please-double-check-dimensions-and-weight-or-try-using/#post-16413060

**Comment by xue28** [comment]
https://wordpress.org/support/topic/no-shipping-rates-for-usps-priority-mail-regional-rate-boxes/#post-16412961

**Comment by laurajohnsonwoo** [comment]
Confirming we have decided to move forward with removing the Regional Rate Boxes altogether. Together with this update, we should show the user a banner message with the copy below, which includes a link to the USPS announcement and WooCommerce documentation about custom packaging. 

Both links should open in a new tab.

> Regional Rate Box prices have been [discontinued by the USPS](https://faq.usps.com/s/article/Regional-Rate-Boxes). Remaining boxes may be used for shipping by entering the dimensions as a [custom package](https://woocommerce.com/document/woocommerce-shipping-and-tax/woocommerce-shipping/#custom-packaging).

**Comment by bartech** [comment]
Solved and closed by PR [#2028](https://github.com/Automattic/woocommerce-connect-server/pull/2028) in [woocommerce-connect-server](https://github.com/Automattic/woocommerce-connect-server)

**Comment by igorhereira** [comment]
https://wordpress.org/support/topic/regional-rate-box-shipping-method-failure/
