### ISSUE TITLE
Fix E2E tests

### ISSUE THREAD

**Issue by waclawjacek** [Automattic/woocommerce-services#2729]
E2E tests are failing. Again. This time with the following error:

<img width="1218" alt="Screenshot 2024-04-12 at 12 45 55" src="https://github.com/Automattic/woocommerce-services/assets/1759681/36cb5e9a-6bc9-4fc2-83fe-252d3f52b134">

Example: https://github.com/Automattic/woocommerce-services/actions/runs/8606963325/job/23586481611

It seems it's just the first job that fails so maybe the container takes a bit longer to spin up and we need to increase the time before we start running the tests? :shrug:

**Comment by iyut** [comment]
It seems the issue is not about the time. I tried to add more timeout like 60000ms. The issue is still there. 
I suspect that puppeteer cannot get the `a#activate-woocommerce-services` element for some reason and I'm still checking on that. I'll update here if I found something.

**Comment by iyut** [comment]
Been trying to replicate the issue on my local. It seems everything working fine on local :
<img width="505" alt="Screenshot 2024-04-23 at 11 26 23" src="https://github.com/Automattic/woocommerce-services/assets/631098/03e07619-54ad-44e0-adda-c5db4cef7244">

Will still continue to look into the issue.

**Comment by iyut** [comment]
Been testing a bunch of times, and here is what I found : 
it seems the issue was when the puppeteer try to go to plugins page after login or update DB page. I also tried to test if the page title contains "Plugins", and the title seems does not contain "Plugins". So I assume, there is some error when puppeteer go from update DB page to any wp-admin page.

When I tried to make it open the other page before plugin page such as WC settings page like what I did in [this commit](https://github.com/Automattic/woocommerce-services/pull/2730/commits/d4db7cafe27cfe09ae6f67ef599d03291527a357), it will work fine afterwards. I also tried to re-run the tests a couple of times just to make sure that it really fix the issue.

At the moment, [this PR](https://github.com/Automattic/woocommerce-services/pull/2730) seems fix the E2E tests. But I still cannot get the reason of the error. WDYT? 
Also, I find myself cannot use `console.log()` to debug. That's why it's kinda hard to debug. Do you guys know a way on how to print something in e2e tests?

**Comment by waclawjacek** [comment]
Very interesting and great digging, @iyut! Thanks for this.

DB updates sound like a possible probable reason. Then again... the E2E tests don't run updates, do they? 🤔 Have you maybe tried what happens if we bump the WP/WC versions we run tests on? (Just asking, no need to do it if you haven't.)

For debugging, have you tried looking at `e2e:dev` and similar scripts in package.json?

**Comment by iyut** [comment]
> DB updates sound like a possible probable reason.

Hi @waclawjacek , TBH I'm still not sure what the reason is. But, DB updates has been done in [this test case](https://github.com/Automattic/woocommerce-services/blob/989482db759de689b648d23d4c6f31458605b31f/tests/e2e/specs/admin/1-activate-extension.test.js#L10).



> For debugging, have you tried looking at `e2e:dev` and similar scripts in package.json?

I've tried debugging using `e2e:dev` as well in my local. But I don't get any issue like in the description as well.
