### ISSUE TITLE
Present a more meaningful error for invalid shipping method instances

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-services#317]
If you attempt to edit the settings for a USPS shipping method instance that no longer exists (or never existed), you get the following.  We can do better :)

![screen shot 2016-05-09 at 4 34 15 pm](https://cloud.githubusercontent.com/assets/1595739/15131359/0bdd33b4-1604-11e6-9ae1-0c4c5ac991d2.png)

**Comment by jkudish** [comment]
Isn't that more of a WC core issue?

**Comment by allendav** [comment]
Yeah, I think you're right - I will take this and move to WC core if need be.

**Comment by allendav** [comment]
Nope - now I remember - this can also happen if a wcc service name is no longer supported (e.g. because the service is deprecated or the name changes in the schema.)  So we need to handle this.

**Comment by jeffstieler** [comment]
> If you attempt to edit the settings for a USPS shipping method instance that no longer exists (or never existed), you get the following. We can do better :)

If we ever retire a shipping method ID, we'll have to come up with a migration plan so users aren't affected.

In order to hit this issue, you'd either have to leave a tab open with the instance, or manually craft the URL to include the now-defunct instance.

Closing - this will have to be avoided as part of retiring a method ID (if that ever occurs).
