### ISSUE TITLE
Include items' shipping classes in rate and label requests

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-services#472]
Right now if an item has a shipping class, e.g. 'media' or 'bees', the server isn't aware of it. In the not distant future, we'll want to be able to tailor the rate or label responses to take shipping classes into account (e.g. to only offer Media Mail service for certain classes, etc)

To make adding that then easier, we should modify the client now to include shipping classes for items in rate and label requests, e.g. here for rates - https://github.com/Automattic/woocommerce-connect-client/blob/master/classes/class-wc-connect-api-client.php#L167

And in a TBD spot for labels (cc @DanReyLop / @jeffstieler )

**Comment by DanReyLop** [comment]
Here to add tht property to the Labels client: https://github.com/Automattic/woocommerce-connect-client/blob/master/classes/class-wc-connect-shipping-label.php#L39

There will also need to be added to the schema: https://github.com/Automattic/woocommerce-connect-client/blob/master/classes/class-wc-connect-shipping-label.php#L290

But shipping classes only will be useful if we populate the available shipping classes when the plug-in is installed (or using a `filter`, I haven't look at the possibilities). Otherwise, we will just receive a flood of merchant-generated classes like `book`, `dvd`, `insect`... that we can't really interpret.

**Comment by laurendavissmith** [comment]
Closing, this seems like something we'll have to investigate further down the road since we'd need a UI to manage this as well
