### ISSUE TITLE
Consider adding checkmark, warning, x next to each instance in Shipping Zones view

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-services#557]
@kellychoffman - this was an idea from the Happiness Academy - just like we show the health of each shipping method instance on the self-help page, what if we did something similar on the shipping zones view, e.g. add a checkmark, warning triangle or error x here:

<img width="1133" alt="screen shot 2016-09-19 at 10 54 13 am" src="https://cloud.githubusercontent.com/assets/1595739/18642968/c2163052-7e57-11e6-845a-b9e8d18da796.png">

**Comment by kellychoffman** [comment]
I had started this a while back, and never got around to posting it. 

I am leaning towards only posting errors and if everything is good, we show nothing. If in error, it should show the same error message as in the system status page when hover/tapped on:

![health-indicator](https://cloud.githubusercontent.com/assets/5835847/19535384/a7643fa0-9604-11e6-8a2b-5d665e981044.png)

**Comment by v18** [comment]
@olaolusoga  - is this type of nudge also a good way to let the user know that they haven't set up their shipping service yet? i.e. to solve part of this issue:

https://github.com/Automattic/woocommerce-services/issues/966

**Comment by olaolusoga** [comment]
@v18 It could potentially. We wouldn't want to show them an error state, since they haven't set anything up yet to get an error.

Best case, when a user first installs WCS, and selects USPS as a shipping method we should take them into the settings, since it's the next step on their path to getting WCS up and running.

The alt would be to show a tooltip like above, but that feels like an unnecessary indicator.

**Comment by laurendavissmith** [comment]
Closed, this is no longer relevant since we're not handling live rates in this extension at the moment
