### ISSUE TITLE
Display estimated delivery date on the front-side for each service

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-services#561]
This idea came from Happiness Academy.  Basically, like amazon does, could we display next to each service option an estimated delivery date?

![img_4459](https://cloud.githubusercontent.com/assets/1595739/18643692/117e868c-7e5b-11e6-8ece-f7b744b46504.JPG)

@jeffstieler - can we get this from EasyPost?

@mikejolley - is this something that would be interesting for core? e.g. adding it to the rates template?

**Comment by DustinHartzler** [comment]
This would be great!

**Comment by jeffstieler** [comment]
@allendav Yep! We can even get estimated delivery dates (for supporting services) directly from USPS. This is also possible with Shippo, but it looks like we'll have to calculate the estimated date ourselves.

This should definitely be an opt-in feature because it relies on the date the item is actually shipped, which is up to the store owner themselves.

**Comment by jconroy** [comment]
Closing in favor of tracking popularity of this feature on the [ideas board](https://ideas.woocommerce.com/forums/133476-woocommerce/suggestions/38747581-display-estimated-delivery-date-on-the-front-side)
