### ISSUE TITLE
Trying to buy a shipping label with no payment method selected: design

### ISSUE THREAD

**Issue by kellychoffman** [Automattic/woocommerce-services#588]
Design task for https://github.com/Automattic/woocommerce-connect-client/issues/549 of the same name

**Comment by jeffstieler** [comment]
This should include any design (if needed) for https://github.com/Automattic/woocommerce-connect-client/issues/447. I think it's just a matter of selecting where to drop a WP admin notice, or perhaps disabling the "create label" button and have some messaging there.

**Comment by jameskoster** [comment]
Here we go;

![cards](https://cldup.com/_FD-7U1QxZ.png)

Any blockers are displayed above the button and the button itself is disabled. I'm not sure we need the info when a card is valid and specified, but I figured it might be a useful option.

Thoughts?

For adding/changing card etc, are we planning to just send folks to https://wordpress.com/me/purchases/ or can we perform those tasks from within wp-admin? If so I'll create an interface for that. Let me know :)

**Comment by jeffstieler** [comment]
> Any blockers are displayed above the button and the button itself is disabled. I'm not sure we need the info when a card is valid and specified, but I figured it might be a useful option.

> Thoughts?

I like this approach a lot - rather than figuring out how to message this from the labels UI, just prevent the user from getting there. Saves a lot of time/frustration. 👍 

Should we have a dismiss option for the "Card added and specified" case? That might get tiresome to see every time you buy a label.

> For adding/changing card etc, are we planning to just send folks to https://wordpress.com/me/purchases/ or can we perform those tasks from within wp-admin? If so I'll create an interface for that. Let me know :)

For adding a card, they'd need to get to the WPCOM/Calypso `/me/purchases/billing` page. Once their cards are stored on WPCOM, they select one from within their wp-admin.

**Comment by jameskoster** [comment]
> Should we have a dismiss option for the "Card added and specified" case? That might get tiresome to see every time you buy a label.

Yeah I thought about the whole tiresome thing. We could de-emphasise the notice a bit? I'm not so keen on making it dismissible because the change/add links could be useful. It'd be frustrating to dismiss the notice then find yourself wanting to click one of those links. That's probably an edge case though. I'll let you decide, but if you'd like me to mock up something which keeps the content but makes the design less prominent I can do that too.

> For adding a card, they'd need to get to the WPCOM/Calypso /me/purchases/billing page. Once their cards are stored on WPCOM, they select one from within their wp-admin.

Cool, I'll mock up the card selection interface.

**Comment by jeffstieler** [comment]
> It'd be frustrating to dismiss the notice then find yourself wanting to click one of those links.

I hadn't thought of that, and agree. Let's leave it for now.

> Cool, I'll mock up the card selection interface.

I just want to make sure that you're aware of our existing interface for this, at `/wp-admin/admin.php?page=wc-settings&tab=connect`. Screenshot:

![screen shot 2017-01-10 at 12 07 14 pm](https://cloud.githubusercontent.com/assets/63922/21820556/6056de3c-d72d-11e6-9628-0a860586b0b9.png)

**Comment by jameskoster** [comment]
Ah yeah, I was just thinking it might be nice to let folks change without leaving the screen. Something like;

![change](https://cldup.com/g6eojyAsj5-3000x3000.png)

Perhaps not for this version, but at some point in the future :)
