### ISSUE TITLE
Connect-a-thon: Support printing test labels

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-services#604]
It might help to be able to print test labels either from the Labels UI or from our Self-Help page.  It would allow the merchant a stress free environment (i.e. no charge) to experiment with print settings / paper settings, etc.

Props @WPprodigy for the idea

**Comment by allendav** [comment]
Assigning for preliminary estimate, please :)

**Comment by DanReyLop** [comment]
If we add it to the self-help page, we'll need either to data-drive it, or to create another, tiny React app and embed it into the same page. The code itself would borrow 90% of the Reprint dialog on the Edit Order page, so there's not much work. I doubt between a 3 and a 5 because of the uncertainty of data-driveness or create another "mini-app". Plus it will need design.

**Comment by jeffstieler** [comment]
This was added to the self help page in feba8c28c19bcd141ea66bb3c6578ea6230eebed.
