### ISSUE TITLE
Design: OK, the merchant opted-in, then what?

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-services#690]
> It felt a bit weird that nothing happened after I clicked “Connect”… nothing visible happened. There was no real indication on what had happened, or my favorite new question: “what next?”. Maybe link directly to the configuration page for Connect or something? I clicked around for a while and eventually found that.

**Comment by allendav** [comment]
Maybe we could do something along these lines and iterate from there?  cc @kellychoffman 

If WooCommerce or Jetpack are not installed, maybe only those two items show up until that's taken care of:

![screen shot 2016-11-11 at 9 24 27 am](https://cloud.githubusercontent.com/assets/1595739/20223963/db67857a-a7f0-11e6-9f8c-73ca5a4ce319.png)

**Comment by jameskoster** [comment]
OK I've been working on this the last couple of days and have something to share. The most challenging thing has been working out the flow given the various scenarios (no wc or jetpack present, just wc present, just jetpack present, etc) by which folks can arrive here.

I'm going to present design solutions for each scenario. But there's a twist - for some scenarios there are two solutions; a simpler notice/pointer driven one, and a more comprehensive wizard-style solution. 

_The designs are rough_ and will be tweaked once we decide on the best approach.

**Scenario the first: WooCommerce is activated, but Jetpack isn't**

*Option 1 - notices*

![install-jetpack](https://cldup.com/n4DF-5aaRz-3000x3000.png)

Simply display a notice asking them to install Jetpack. Clicking the button will install Jetpack and prompt the WordPress.com connection.

![setup-usps](https://cldup.com/ZOBjY9E9BM-3000x3000.png)

Once that process is complete, display a notice asking them to begin setting up USPS (or Canada Post, depending on their base location). Clicking the button in this notice will take them to the settings screen and use [WordPress pointers](http://kakoma.ug/wp-content/uploads/2015/02/wordpress_admin_pointers.jpeg) to guide them through it.

I haven't mocked that up, hopefully you can use your imagination xD

*Option 2 - Wizard*

![wizard](https://cldup.com/9M9S5LSRCM.png)

The wizard will ask them to install Jetpack first (if it's not already) and then takes them through the separate steps required to configure USPS or Canada Post.

**Scenario the second: Neither WooCommerce nor Jetpack are activated**

This scenario is actually quite straight-forward and probably extremely rare. We simply ask them to install WooCommerce like so:

![install-wc](https://cldup.com/MEXllitNzo-2000x2000.png)

After-which they are automatically launched into the WooCommerce set up wizard in which we've already designed the [Jetpack connection flow](https://heyhydra.wordpress.com/2016/11/11/connect-for-woocommerce-connection-flow-jetpack-forward/).

In addition to that connection flow, we can add a section to the 'Shipping & Tax' step in the wizard to setup USPS or Canada Post. Something like;

![setup-shipping](https://cldup.com/WZbymK8T6U.png)

We can improve this much further when we redesign the set up wizard in s9n.

This is pretty much how I envisage setup to work if/when Connect becomes a part of WooCommerce core.

**Scenario the third: Both WooCommerce and Jetpack are already installed and activated**

*Option 1 - notices*
Here we can simply display a notice guiding users to the settings screen to set up shipping with assistance from notices.

![jump-in](https://cldup.com/FePkMJxZi6.png)

*Option 2 - wizard*

The wizard would be exactly the same as before:

![wizard](https://cldup.com/9M9S5LSRCM.png)

Except the first step will be skipped and shown as completed.

**Moving forwards**
Personally I prefer the wizard approach because it makes configuring the shipping settings simpler by breaking it down into a few steps. WordPress Pointers are quite controversial and there are several plugins around to disable the feature entirely.

Of course, building a wizard is quite a bit more work. So I wonder if we do both? The simple notice/pointer solution for now and the wizard later.

**Comment by allendav** [comment]
Thank you @jameskoster !  My thoughts:

Thought 1 : Let's add a new scenario (zero) for when woocommerce is active, jetpack is missing, and the base location is outside the US or Canada.  We should tell them that services are not yet available in their area, but invite them to try Jetpack anyways (or dismiss the prompt with a promise that if they leave connect active, we'll let them know when services are available in their area)  (In a future update to the client, when a non North American option is available, we can display a new banner them to invite them to join the party. The merchant will see this on updating connect.)

Thought 2 : For scenario 1 (woocommerce active, but jetpack missing) - could we replace that "Install Jetpack and connect to WordPress.com" button with a AJAX powered button like @kellychoffman has proposed for the Setup Wizard NUX, e.g.:

![screen shot 2016-11-18 at 1 08 11 pm](https://cloud.githubusercontent.com/assets/1595739/20446762/233e18b0-ad90-11e6-8f48-8df55e0cc157.png)

and then send them over to jetpack to complete their connection, and then return them to their wp-admin to invite them to set up USPS or Canada Post?

Thought 3: The wizard is pretty, but it duplicates a lot of our USPS and Canada Post shipping method user interfaces and. Is there a happy middle we could try where we

1) use a notice that invites them to set up connect powered shipping and includes:
2) a prompt for the postal code they ship from 
3) a list (SELECT?) of zones that includes:
their existing zones that include the US ( if their base location is US )
their existing zones that include Canada ( if their base location is Canada )
an option to "Create a new Zone"
3) a button to "Setup USPS" (or Canada Post)
4) that button will create a zone if needed, add a shipping method instance to the zone and take them to the new shipping method instance where they will find
5) the postal code has been filled in for them and...
6) a few popular services have been preselected (e.g. Priority Mail) and...
7) tells them they are all set and prompts them to review their settings

Whatcha think?  We could avoid further fattening up the setup wizard shipping step by launching this prompt after WooCommerce Setup is complete too (instead of adding zone setup and rate selection on that tab.)

ccing @mikejolley and @kellychoffman for their thoughts too

**Comment by jameskoster** [comment]
Cheers @allendav :)

> Let's add a new scenario (zero) for when woocommerce is active, jetpack is missing, and the base location is outside the US or Canada. We should tell them that services are not yet available in their area, but invite them to try Jetpack anyways (or dismiss the prompt with a promise that if they leave connect active, we'll let them know when services are available in their area) (In a future update to the client, when a non North American option is available, we can display a new banner them to invite them to join the party. The merchant will see this on updating connect.)

Do you mean we'd be able to inform them _without_ them having to update the client? I'm a little hesitant to recommend leaving a plugin active if it's not being used. There's a (very slim) security risk and if their site ever feels slow it could reflect poorly on us if they perceive Connect to be a contributing factor (even if _we_ know it isn't). Could we ask them to subscribe to a mailing list instead?

> Thought 2 : For scenario 1 (woocommerce active, but jetpack missing) - could we replace that "Install Jetpack and connect to WordPress.com" button with a AJAX powered button like @kellychoffman has proposed for the Setup Wizard NUX, e.g.:

> and then send them over to jetpack to complete their connection, and then return them to their wp-admin to invite them to set up USPS or Canada Post?

I should have explained it better but that is pretty much exactly how I see it working. It's basically 2 notices. One asking them to install Jetpack (with an AJAX button) and another that appears when Jetpack is connected asking them to configure their shipping settings.

> The wizard is pretty, but it duplicates a lot of our USPS and Canada Post shipping method user interfaces. Is there a happy middle we could try where we

This proposed flow would work fine when WooCommerce is activated and Jetpack isn't, or when both WooCommerce and Jetpack are activated, as an alternative to the wizard.

But I still think it would be neater if we could integrate with the current WooCommerce wizard in the case that WooCommerce isn't activated. I admit it does 'fatten' it up a bit, but the flow seems a little odd to me if we ask folks to configure their shipping settings in cores wizard and then ask them to do it again (for Connect) when they're finished with the wizard. It's the same number of steps, but one is contained in the wizard and one kinda looks like an after-thought. I know it's extra dev time to do this though, so maybe it comes in a future release?

**Comment by allendav** [comment]
> Do you mean we'd be able to inform them without them having to update the client? I'm a little hesitant to recommend leaving a plugin active if it's not being used. There's a (very slim) security risk and if their site ever feels slow it could reflect poorly on us if they perceive Connect to be a contributing factor (even if we know it isn't). Could we ask them to subscribe to a mailing list instead?

Excellent point. Yes - mailing list

**Comment by allendav** [comment]
> But I still think it would be neater if we could integrate with the current WooCommerce wizard in the case that WooCommerce isn't activated. I admit it does 'fatten' it up a bit, but the flow seems a little odd to me if we ask folks to configure their shipping settings in cores wizard and then ask them to do it again (for Connect) when they're finished with the wizard.

Ya know, let's ask US and Canadian merchants for their postal code and let's see if core has any plans around adding zones during setup wizard - maybe we could prompt the user for permission to add USPS or Canada Post (as appropriate) to a zone during the wizard using the postal code, select a few popular services for them (e.g. Priority Mail), and invite them to edit their settings in more detail later? cc @mikejolley 

Fwiw, we probably need to sit on this until next week so we can clarify the delivery mechanism for connect.

**Comment by jameskoster** [comment]
> Fwiw, we probably need to sit on this until next week so we can clarify the delivery mechanism for connect.

Agreed.

**Comment by allendav** [comment]
Moving to Sprint 10

**Comment by allendav** [comment]
And, based on The Direction chat, now moving this out of any sprint

**Comment by jeffstieler** [comment]
Closing this - will get taken care of (read: written as new issues) in some upcoming NUX efforts.
