### ISSUE TITLE
Add support for domestic shipping that WooCommerce core treats as international

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-services#846]
Sorry for another drive-by issue. I just ran into this on a different shipping extension of ours. WooCommerce core (as of 2.6?) treats these domestic addresses as international, so it would be good 1) to be aware that this means that connect 1.0 doesn't support these in case support questions come up as they will and 2) to be sure that these destinations don't require customs forms if they do not need to when they are implemented in connect.

Domestic, no Customs Forms
PR	Puerto Rico
VI	United States (US) Virgin Islands

Domestic, but requires Custom Forms
AS	American Samoa
GU	Guam
MP	Northern Mariana Islands
UM	United States (US) Minor Outlying Islands

"Compact of Free Association" countries (treated as domestic destinations, but it is not clear about customs forms)
FM	Federated States of Micronesia
MH	Marshall Islands
PW	Palau

**Comment by WPprodigy** [comment]
Two of them are mentioned here: https://github.com/woocommerce/woocommerce/blob/906b7dbf10eba9da49c1abe24bf5668bdc99f030/i18n/countries.php

Here is the error report from a customer that is pretty detailed: 

> When trying to calculate shipping for the Marshall Islands, the error below is logged:

> 07-11-2017 @ 18:21:14 - Error. Unable to get shipping rate(s) for wc_services_usps instance id 6. (calculate_shipping) 
07-11-2017 @ 18:21:14 - wcc_server_error_response Error: The WooCommerce Services server returned: Bad Request child "destination" fails because [child "country" fails because ["country" must be one of [AF, AX, AL, DZ, AS, AD, AO, AI, AG, AR, AM, AW, AU, AT, AZ, BS, BH, BD, BB, BY, BE, BZ, BJ, BM, BT, BO, BQ, BA, BW, BV, BR, IO, VG, BN, BG, BF, BI, KH, CM, CA, CV, KY, CF, TD, CL, CN, CX, CC, CO, KM, CG, CD, CK, CR, HR, CU, CW, CY, CZ, DK, DJ, DM, DO, EC, EG, SV, GQ, ER, EE, ET, FK, FO, FJ, FI, FR, GF, PF, TF, GA, GM, GE, DE, GH, GI, GR, GL, GD, GP, GU, GT, GG, GN, GW, GY, HT, HM, HN, HK, HU, IS, IN, ID, IR, IQ, IE, IM, IL, IT, CI, JM, JP, JE, JO, KZ, KE, KI, KW, KG, LA, LV, LB, LS, LR, LY, LI, LT, LU, MO, MK, MG, MW, MY, MV, ML, MT, MQ, MR, MU, YT, MX, MD, MC, MN, ME, MS, MA, MZ, MM, NA, NR, NP, NL, NC, NZ, NI, NE, NG, NU, NF, MP, KP, NO, OM, PK, PS, PA, PG, PY, PE, PH, PN, PL, PT, PR, QA, RE, RO, RU, RW, BL, SH, KN, LC, MF, SX, PM, VC, SM, ST, SA, SN, RS, SC, SL, SG, SK, SI, SB, SO, ZA, GS, KR, ES, LK, SD, SR, SJ, SZ, SE, CH, SY, TW, TJ, TZ, TH, TL, TG, TK, TO, TT, TN, TR, TM, TC, TV, UG, UA, AE, GB, US, UM, VI, UY, UZ, VU, VA, VE, VN, WF, EH, WS, YE, ZM, ZW]]] ( 400 ) (calculate_shipping)

> It looks like it won't recognize the Republic of the Marshall Islands, the Federated States of Micronesia and the Republic of Palau.

> Please be aware that since 1986, due to the Compact of Free Association between those countries and the USA, these countries and the USA SHARE the US Postal Service, and all shipping to those countries are DOMESTIC rates.

https://woothemes.zendesk.com/agent/tickets/600537

CC @jeffstieler

**Comment by jeffstieler** [comment]
Considering closed by: https://github.com/Automattic/wp-calypso/pull/23829
