### ISSUE TITLE
Awkward placement of “Other Services” in list

### ISSUE THREAD

**Issue by joelwills** [Automattic/woocommerce-services#948]
![Screenshot](https://cloudup.com/cr9RPeR8Mru+)

Link to image: https://cloudup.com/cr9RPeR8Mru

This should probably be moved to the bottom based on likely low usage, though it is currently in alphabetical order which appeals!

**Comment by jeffstieler** [comment]
Perhaps this should also be renamed to "Specialty Services" or something to that effect. Many of those services have specific requirements for usage.

(cc: @olaolusoga)

**Comment by joelwills** [comment]
"Speciality" as I'm British and live extra letters in words ;)

**Comment by olaolusoga** [comment]
@jeffstieler  Ideally the label should help users with comprehension around the option, though "Specialty Services" sounds more on point, curious if it could obfuscate the message by giving users the perception that it's a "special" service.

"Other services" feels more correct, since most users will expand to read more before selecting (an assumption), which is what we want them to do for this option.

**Comment by DanReyLop** [comment]
Just adding to this: The service groups are sorted based on `group_id` (*not* by name), so we could rename `other_services` to `z_other_services` without changing the `Other Services` label :)

**Comment by dechov** [comment]
Beyond just this one service group, do we prefer to preserve alphabetical order, or is there a specific curated order that would make more sense? I see the services themselves are not sorted beyond how it is stored on the server — is this the preferred / intentional ordering? — and we could presumably do the same for the groups:

Priority Mail, Priority Mail Express, First-Class Mail, Other Services, Priority Mail Express International, Priority Mail International, First-Class International

...which exactly matches a concatenation of https://www.usps.com/ship/mail-shipping-services.htm and https://www.usps.com/international/mail-shipping-services.htm

Note that this would put "Other Services" in the middle instead of the end, before the international services (also similar to [this list at ebay.com](http://pages.ebay.com/help/pay/shipping-services.html#shippingservices)).

If, on the other hand, we do want to preserve the current alphabetical ordering of groups, shall we go ahead with the alphabetical maneuvering proposed by @DanReyLop?

**Comment by olaolusoga** [comment]
On the front end, the order should be predicated on what provides both the store owner and WCS the most value (price, speed). Since we currently only offer national options, it'd make sense to hide/remove the international offerings until it's something we can offer the user.

**Comment by DanReyLop** [comment]
> Since we currently only offer national options, it'd make sense to hide/remove the international offerings until it's something we can offer the user.

We only offer national options **for shipping labels**, but shipping rates are a separate feature. I wouldn't be confortable removing functionality this late in the plugin life.

**Comment by olaolusoga** [comment]
Makes sense @danreylop ... are we tracking usage of the rate options? It'd be great to get a gauge on what ppl are using. Aside from that, maybe we leave the list as is for now. Shipping improvements is on the list for Q3 and we can circle back.
